// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBespSm5NOmCc_KMi5CS19zo4OydoMoY',
    appId: '1:506701806691:web:0dd8071fd10b8586738c56',
    messagingSenderId: '506701806691',
    projectId: 'neon-flight',
    authDomain: 'neon-flight.firebaseapp.com',
    storageBucket: 'neon-flight.firebasestorage.app',
    measurementId: 'G-MBH6Z89QNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtTGy7d5rt6ydh0kG6UwtVmoYxZ31NyU',
    appId: '1:506701806691:android:357da75b5a1a8de1738c56',
    messagingSenderId: '506701806691',
    projectId: 'neon-flight',
    storageBucket: 'neon-flight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8ICCU6YgR9E5Qb5qf_c-KaZbB5SacFc',
    appId: '1:506701806691:ios:4d044d85a45246e7738c56',
    messagingSenderId: '506701806691',
    projectId: 'neon-flight',
    storageBucket: 'neon-flight.firebasestorage.app',
    iosBundleId: 'com.example.miniProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYBespSm5NOmCc_KMi5CS19zo4OydoMoY',
    appId: '1:506701806691:web:fd207c0bcdfd9f1c738c56',
    messagingSenderId: '506701806691',
    projectId: 'neon-flight',
    authDomain: 'neon-flight.firebaseapp.com',
    storageBucket: 'neon-flight.firebasestorage.app',
    measurementId: 'G-B911JKB1N3',
  );
}
