class AppLanguage {
  const AppLanguage(this.code, this.name, this.nativeName, this.flag);
  final String code;
  final String name;
  final String nativeName;
  final String flag;
}

const supportedLanguages = <AppLanguage>[
  AppLanguage('th', 'Thai', 'ไทย', '🇹🇭'),
  AppLanguage('en', 'English', 'English', '🇬🇧'),
  AppLanguage('ja', 'Japanese', '日本語', '🇯🇵'),
  AppLanguage('zh', 'Chinese', '中文', '🇨🇳'),
  AppLanguage('ko', 'Korean', '한국어', '🇰🇷'),
];

const Map<String, Map<String, String>> _strings = {
  'th': {
    'home':'หน้าหลัก','bookings':'การจอง','profile':'โปรไฟล์','hello':'สวัสดี',
    'where_today':'วันนี้อยากบินไปที่ไหน?','special_deals':'ดีลราคาพิเศษ','popular_destinations':'จุดหมายยอดนิยม',
    'notifications':'การแจ้งเตือน','no_notifications':'ยังไม่มีการแจ้งเตือนใหม่',
    'one_way':'เที่ยวเดียว','round_trip':'ไป-กลับ','from':'จาก','to':'ไป','swap':'สลับเส้นทาง',
    'cabin_class':'ชั้นโดยสาร','passengers':'ผู้โดยสาร','adult':'ผู้ใหญ่','child':'เด็ก','search_flight':'ค้นหาเที่ยวบิน',
    'remaining':'เหลือ','seats':'ที่นั่ง','view_flights':'ดูเที่ยวบิน','no_deals':'ยังไม่มีดีลในขณะนี้',
    'economy':'ชั้นประหยัด','premium_economy':'ชั้นประหยัดพรีเมียม','business':'ชั้นธุรกิจ','first':'ชั้นหนึ่ง',
    'my_account':'บัญชีของฉัน','preferences':'การตั้งค่า','personal_info':'ข้อมูลส่วนตัว','personal_info_sub':'ชื่อ เบอร์โทร ที่อยู่',
    'saved_passengers':'ผู้โดยสารที่บันทึกไว้','saved_passengers_sub':'จัดการข้อมูลผู้โดยสาร',
    'passport':'หนังสือเดินทาง','passport_sub':'จัดการข้อมูลหนังสือเดินทาง',
    'payment_methods':'วิธีชำระเงิน','payment_methods_sub':'บัตรและช่องทางที่บันทึกไว้',
    'dark_mode':'โหมดมืด','language':'ภาษา','choose_language':'เลือกภาษา','logout':'ออกจากระบบ',
    'logout_confirm':'ต้องการออกจากระบบหรือไม่?','cancel':'ยกเลิก','save':'บันทึก','saved':'บันทึกข้อมูลเรียบร้อย',
    'add':'เพิ่ม','full_name':'ชื่อ-นามสกุล','phone':'เบอร์โทรศัพท์','address':'ที่อยู่','add_passenger':'เพิ่มผู้โดยสาร',
    'no_passengers':'ยังไม่มีผู้โดยสารที่บันทึกไว้','passport_number':'หมายเลขหนังสือเดินทาง','nationality':'สัญชาติ',
    'my_bookings':'การจองของฉัน','upcoming':'กำลังจะเดินทาง','completed':'เสร็จสิ้น','cancelled':'ยกเลิกแล้ว',
    'no_booking':'ยังไม่มีรายการ','no_booking_sub':'การจองในสถานะนี้จะแสดงที่นี่','view_ticket':'ดูตั๋ว',
    'passenger_info':'ข้อมูลผู้โดยสาร','title':'คำนำหน้า','first_name':'ชื่อ','last_name':'นามสกุล','birth_date':'วันเกิด',
    'passport_expiry':'วันหมดอายุหนังสือเดินทาง','required':'กรุณากรอกข้อมูล','invalid_email':'Email ไม่ถูกต้อง','select_seat':'เลือกที่นั่ง',
    'available':'ว่าง','selected':'ที่เลือก','unavailable':'ไม่ว่าง','front':'ด้านหน้า','please_select':'กรุณาเลือกที่นั่ง',
    'selected_seats':'ที่นั่งที่เลือก','continue':'ดำเนินการต่อ','seat_fee':'ค่าที่นั่ง',
    'payment':'ชำระเงิน','payment_method':'วิธีชำระเงิน','scan_promptpay':'สแกน QR PromptPay เพื่อชำระเงิน',
    'fare':'ค่าโดยสาร','airport_tax':'ภาษีสนามบิน','service_fee':'ค่าบริการ','total':'ยอดรวม','confirm_pay':'ยืนยันและชำระเงิน',
    'mobile_bank_info':'ระบบจำลองจะเปิดแอปธนาคารและกลับมายืนยันการชำระเงิน',
    'sort_by':'เรียงตาม','cheapest':'ราคาถูกสุด','earliest':'ออกเร็วสุด','fastest':'บินเร็วสุด','max_price':'ราคาสูงสุด',
    'load_failed':'โหลดเที่ยวบินไม่สำเร็จ','retry':'ลองใหม่','no_flights':'ไม่พบเที่ยวบิน',
    'no_flights_sub':'ลองเปลี่ยนวันที่ เส้นทาง หรือช่วงราคา','search_again':'ค้นหาใหม่','direct':'บินตรง','hours':'ชม.','minutes':'นาที',
    'select':'เลือก','login_tagline':'จองเที่ยวบินง่าย ครบทุกขั้นตอน','remember_me':'จดจำฉัน','forgot_password':'ลืมรหัสผ่าน?',
    'login':'เข้าสู่ระบบ','create_account':'สร้างบัญชีใหม่','register':'สมัครสมาชิก','register_title':'สร้างบัญชี',
    'password_min':'Password อย่างน้อย 6 ตัว','reset_sent':'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว',
    'download':'ดาวน์โหลด','share':'แชร์','downloaded':'บันทึก E-Ticket แล้ว (Demo)','share_opened':'เปิดเมนูแชร์แล้ว (Demo)',
    'passenger':'ผู้โดยสาร','flight':'เที่ยวบิน','date':'วันที่','time':'เวลา','seat':'ที่นั่ง','class':'ชั้นโดยสาร',
  },
  'en': {
    'home':'Home','bookings':'Bookings','profile':'Profile','hello':'Hello',
    'where_today':'Where would you like to fly today?','special_deals':'Special deals','popular_destinations':'Popular destinations',
    'notifications':'Notifications','no_notifications':'No new notifications',
    'one_way':'One way','round_trip':'Round trip','from':'From','to':'To','swap':'Swap route',
    'cabin_class':'Cabin class','passengers':'Passengers','adult':'Adults','child':'Children','search_flight':'Search flights',
    'remaining':'Only','seats':'seats left','view_flights':'View flights','no_deals':'No special deals available',
    'economy':'Economy Class','premium_economy':'Premium Economy','business':'Business Class','first':'First Class',
    'my_account':'My account','preferences':'Preferences','personal_info':'Personal information','personal_info_sub':'Name, phone and address',
    'saved_passengers':'Saved passengers','saved_passengers_sub':'Manage passenger information',
    'passport':'Passport','passport_sub':'Manage passport information',
    'payment_methods':'Payment methods','payment_methods_sub':'Saved cards and payment options',
    'dark_mode':'Dark mode','language':'Language','choose_language':'Choose language','logout':'Log out',
    'logout_confirm':'Do you want to log out?','cancel':'Cancel','save':'Save','saved':'Information saved',
    'add':'Add','full_name':'Full name','phone':'Phone number','address':'Address','add_passenger':'Add passenger',
    'no_passengers':'No saved passengers','passport_number':'Passport number','nationality':'Nationality',
    'my_bookings':'My bookings','upcoming':'Upcoming','completed':'Completed','cancelled':'Cancelled',
    'no_booking':'No bookings yet','no_booking_sub':'Bookings with this status will appear here','view_ticket':'View ticket',
    'passenger_info':'Passenger information','title':'Title','first_name':'First name','last_name':'Last name','birth_date':'Birth date',
    'passport_expiry':'Passport expiry','required':'This field is required','invalid_email':'Invalid email','select_seat':'Select seat',
    'available':'Available','selected':'Selected','unavailable':'Unavailable','front':'FRONT','please_select':'Please select your seat',
    'selected_seats':'Selected seats','continue':'Continue','seat_fee':'Seat fee',
    'payment':'Payment','payment_method':'Payment method','scan_promptpay':'Scan PromptPay QR to pay',
    'fare':'Fare','airport_tax':'Airport tax','service_fee':'Service fee','total':'Total','confirm_pay':'Confirm and pay',
    'mobile_bank_info':'The demo will open a banking app and return to confirm payment',
    'sort_by':'Sort by','cheapest':'Cheapest','earliest':'Earliest','fastest':'Fastest','max_price':'Max price',
    'load_failed':'Could not load flights','retry':'Retry','no_flights':'No flights found',
    'no_flights_sub':'Try another date, route, or price range','search_again':'Search again','direct':'Direct','hours':'h','minutes':'m',
    'select':'Select','login_tagline':'Book flights easily from search to ticket','remember_me':'Remember me','forgot_password':'Forgot password?',
    'login':'Log in','create_account':'Create account','register':'Register','register_title':'Create account',
    'password_min':'Password (at least 6 characters)','reset_sent':'Password reset link sent',
    'download':'Download','share':'Share','downloaded':'E-Ticket saved (Demo)','share_opened':'Share menu opened (Demo)',
    'passenger':'Passenger','flight':'Flight','date':'Date','time':'Time','seat':'Seat','class':'Class',
  },
  'ja': {
    'home':'ホーム','bookings':'予約','profile':'プロフィール','hello':'こんにちは',
    'where_today':'今日はどこへ行きますか？','special_deals':'特別オファー','popular_destinations':'人気の目的地',
    'notifications':'通知','no_notifications':'新しい通知はありません',
    'one_way':'片道','round_trip':'往復','from':'出発地','to':'目的地','swap':'入れ替え',
    'cabin_class':'座席クラス','passengers':'乗客','adult':'大人','child':'子供','search_flight':'フライトを検索',
    'remaining':'残り','seats':'席','view_flights':'フライトを見る','no_deals':'現在特別オファーはありません',
    'economy':'エコノミークラス','premium_economy':'プレミアムエコノミー','business':'ビジネスクラス','first':'ファーストクラス',
    'my_account':'マイアカウント','preferences':'設定','personal_info':'個人情報','personal_info_sub':'名前・電話番号・住所',
    'saved_passengers':'保存済みの乗客','saved_passengers_sub':'乗客情報を管理','passport':'パスポート','passport_sub':'パスポート情報を管理',
    'payment_methods':'支払い方法','payment_methods_sub':'保存済みのカードと支払い方法','dark_mode':'ダークモード','language':'言語',
    'choose_language':'言語を選択','logout':'ログアウト','logout_confirm':'ログアウトしますか？','cancel':'キャンセル','save':'保存',
    'saved':'保存しました','add':'追加','full_name':'氏名','phone':'電話番号','address':'住所','add_passenger':'乗客を追加',
    'no_passengers':'保存された乗客はいません','passport_number':'パスポート番号','nationality':'国籍',
    'my_bookings':'予約','upcoming':'今後','completed':'完了','cancelled':'キャンセル済み','no_booking':'予約はありません',
    'no_booking_sub':'この状態の予約がここに表示されます','view_ticket':'チケットを見る',
    'passenger_info':'乗客情報','title':'敬称','first_name':'名','last_name':'姓','birth_date':'生年月日','passport_expiry':'パスポート有効期限',
    'required':'入力してください','invalid_email':'メールアドレスが無効です','select_seat':'座席を選択','available':'空席','selected':'選択済み',
    'unavailable':'利用不可','front':'前方','please_select':'座席を選択してください','selected_seats':'選択した座席','continue':'続ける','seat_fee':'座席料金',
    'payment':'支払い','payment_method':'支払い方法','scan_promptpay':'PromptPay QRをスキャンして支払う',
    'fare':'運賃','airport_tax':'空港税','service_fee':'サービス料','total':'合計','confirm_pay':'確認して支払う',
    'mobile_bank_info':'デモでは銀行アプリを開き、支払い確認に戻ります',
    'sort_by':'並び替え','cheapest':'最安','earliest':'最早出発','fastest':'最短','max_price':'最高価格','load_failed':'フライトを読み込めません',
    'retry':'再試行','no_flights':'フライトが見つかりません','no_flights_sub':'日付・路線・価格帯を変更してください','search_again':'再検索',
    'direct':'直行便','hours':'時間','minutes':'分','select':'選択',
    'login_tagline':'検索からチケットまで簡単に予約','remember_me':'ログイン状態を保持','forgot_password':'パスワードを忘れた場合',
    'login':'ログイン','create_account':'アカウント作成','register':'登録','register_title':'アカウント作成',
    'password_min':'パスワード（6文字以上）','reset_sent':'リセットリンクを送信しました',
    'download':'ダウンロード','share':'共有','downloaded':'E-Ticketを保存しました（デモ）','share_opened':'共有メニューを開きました（デモ）',
    'passenger':'乗客','flight':'便名','date':'日付','time':'時刻','seat':'座席','class':'クラス',
  },
  'zh': {
    'home':'首页','bookings':'预订','profile':'个人资料','hello':'你好','where_today':'今天想飞去哪里？',
    'special_deals':'特别优惠','popular_destinations':'热门目的地','notifications':'通知','no_notifications':'暂无新通知',
    'one_way':'单程','round_trip':'往返','from':'出发地','to':'目的地','swap':'交换路线','cabin_class':'舱位','passengers':'乘客',
    'adult':'成人','child':'儿童','search_flight':'搜索航班','remaining':'剩余','seats':'个座位','view_flights':'查看航班','no_deals':'暂无特别优惠',
    'economy':'经济舱','premium_economy':'高级经济舱','business':'商务舱','first':'头等舱','my_account':'我的账户','preferences':'设置',
    'personal_info':'个人信息','personal_info_sub':'姓名、电话和地址','saved_passengers':'已保存乘客','saved_passengers_sub':'管理乘客信息',
    'passport':'护照','passport_sub':'管理护照信息','payment_methods':'付款方式','payment_methods_sub':'已保存的银行卡和付款方式',
    'dark_mode':'深色模式','language':'语言','choose_language':'选择语言','logout':'退出登录','logout_confirm':'确定要退出登录吗？',
    'cancel':'取消','save':'保存','saved':'保存成功','add':'添加','full_name':'姓名','phone':'电话号码','address':'地址',
    'add_passenger':'添加乘客','no_passengers':'暂无已保存乘客','passport_number':'护照号码','nationality':'国籍',
    'my_bookings':'我的预订','upcoming':'即将出行','completed':'已完成','cancelled':'已取消','no_booking':'暂无预订',
    'no_booking_sub':'此状态的预订将显示在这里','view_ticket':'查看机票','passenger_info':'乘客信息','title':'称谓','first_name':'名',
    'last_name':'姓','birth_date':'出生日期','passport_expiry':'护照到期日','required':'请填写此项','invalid_email':'邮箱格式不正确',
    'select_seat':'选择座位','available':'可选','selected':'已选择','unavailable':'不可选','front':'前方','please_select':'请选择座位',
    'selected_seats':'已选座位','continue':'继续','seat_fee':'选座费','payment':'付款','payment_method':'付款方式',
    'scan_promptpay':'扫描 PromptPay 二维码付款','fare':'票价','airport_tax':'机场税','service_fee':'服务费','total':'总计',
    'confirm_pay':'确认并付款','mobile_bank_info':'演示将打开银行应用并返回确认付款','sort_by':'排序','cheapest':'最低价','earliest':'最早出发',
    'fastest':'最快','max_price':'最高价格','load_failed':'航班加载失败','retry':'重试','no_flights':'未找到航班',
    'no_flights_sub':'请尝试更改日期、航线或价格范围','search_again':'重新搜索','direct':'直飞','hours':'小时','minutes':'分钟','select':'选择',
    'login_tagline':'从搜索到出票，轻松预订航班','remember_me':'记住我','forgot_password':'忘记密码？','login':'登录',
    'create_account':'创建账户','register':'注册','register_title':'创建账户','password_min':'密码（至少6位）','reset_sent':'重置链接已发送',
    'download':'下载','share':'分享','downloaded':'E-Ticket 已保存（演示）','share_opened':'已打开分享菜单（演示）',
    'passenger':'乘客','flight':'航班','date':'日期','time':'时间','seat':'座位','class':'舱位',
  },
  'ko': {
    'home':'홈','bookings':'예약','profile':'프로필','hello':'안녕하세요','where_today':'오늘 어디로 떠나시겠어요?',
    'special_deals':'특가 상품','popular_destinations':'인기 여행지','notifications':'알림','no_notifications':'새로운 알림이 없습니다',
    'one_way':'편도','round_trip':'왕복','from':'출발','to':'도착','swap':'경로 변경','cabin_class':'좌석 등급','passengers':'승객',
    'adult':'성인','child':'어린이','search_flight':'항공편 검색','remaining':'남은 좌석','seats':'석','view_flights':'항공편 보기','no_deals':'현재 특별 할인이 없습니다',
    'economy':'이코노미 클래스','premium_economy':'프리미엄 이코노미','business':'비즈니스 클래스','first':'퍼스트 클래스',
    'my_account':'내 계정','preferences':'설정','personal_info':'개인 정보','personal_info_sub':'이름, 전화번호 및 주소',
    'saved_passengers':'저장된 승객','saved_passengers_sub':'승객 정보 관리','passport':'여권','passport_sub':'여권 정보 관리',
    'payment_methods':'결제 수단','payment_methods_sub':'저장된 카드 및 결제 방법','dark_mode':'다크 모드','language':'언어','choose_language':'언어 선택',
    'logout':'로그아웃','logout_confirm':'로그아웃하시겠습니까?','cancel':'취소','save':'저장','saved':'저장되었습니다','add':'추가',
    'full_name':'이름','phone':'전화번호','address':'주소','add_passenger':'승객 추가','no_passengers':'저장된 승객이 없습니다',
    'passport_number':'여권 번호','nationality':'국적','my_bookings':'내 예약','upcoming':'예정','completed':'완료','cancelled':'취소',
    'no_booking':'예약이 없습니다','no_booking_sub':'이 상태의 예약이 여기에 표시됩니다','view_ticket':'티켓 보기','passenger_info':'승객 정보',
    'title':'호칭','first_name':'이름','last_name':'성','birth_date':'생년월일','passport_expiry':'여권 만료일','required':'필수 입력 항목입니다',
    'invalid_email':'이메일 형식이 올바르지 않습니다','select_seat':'좌석 선택','available':'선택 가능','selected':'선택됨','unavailable':'사용 불가',
    'front':'앞쪽','please_select':'좌석을 선택해 주세요','selected_seats':'선택한 좌석','continue':'계속','seat_fee':'좌석 요금',
    'payment':'결제','payment_method':'결제 수단','scan_promptpay':'PromptPay QR을 스캔하여 결제','fare':'운임','airport_tax':'공항세',
    'service_fee':'서비스 수수료','total':'총액','confirm_pay':'확인 및 결제','mobile_bank_info':'데모에서는 은행 앱을 열고 결제 확인으로 돌아옵니다',
    'sort_by':'정렬','cheapest':'최저가','earliest':'가장 이른 출발','fastest':'최단 시간','max_price':'최고 가격','load_failed':'항공편을 불러오지 못했습니다',
    'retry':'다시 시도','no_flights':'항공편이 없습니다','no_flights_sub':'날짜, 노선 또는 가격 범위를 변경해 보세요','search_again':'다시 검색',
    'direct':'직항','hours':'시간','minutes':'분','select':'선택','login_tagline':'검색부터 티켓까지 간편하게 예약',
    'remember_me':'로그인 유지','forgot_password':'비밀번호를 잊으셨나요?','login':'로그인','create_account':'계정 만들기','register':'가입',
    'register_title':'계정 만들기','password_min':'비밀번호(6자 이상)','reset_sent':'재설정 링크를 보냈습니다',
    'download':'다운로드','share':'공유','downloaded':'E-Ticket을 저장했습니다(데모)','share_opened':'공유 메뉴를 열었습니다(데모)',
    'passenger':'승객','flight':'항공편','date':'날짜','time':'시간','seat':'좌석','class':'클래스',
  },
};

String tr(String languageCode, String key) =>
    _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;

String cityName(String lang, String code, {String? cityTh, String? cityEn}) {
  const map = {
    'BKK': {'ja':'バンコク','zh':'曼谷','ko':'방콕'},
    'CNX': {'ja':'チェンマイ','zh':'清迈','ko':'치앙마이'},
    'HKT': {'ja':'プーケット','zh':'普吉','ko':'푸켓'},
    'NRT': {'ja':'東京','zh':'东京','ko':'도쿄'},
    'ICN': {'ja':'ソウル','zh':'首尔','ko':'서울'},
    'SIN': {'ja':'シンガポール','zh':'新加坡','ko':'싱가포르'},
  };
  if (lang == 'th') return cityTh ?? code;
  if (lang == 'en') return cityEn ?? code;
  return map[code]?[lang] ?? cityEn ?? cityTh ?? code;
}
