class AppLanguage {
  const AppLanguage(this.code, this.name, this.nativeName, this.flag);
  final String code;
  final String name;
  final String nativeName;
  final String flag;
}

const supportedLanguages = <AppLanguage>[
  AppLanguage('th', 'Thai', 'ไทย', '🇹🇭'),
  AppLanguage('en', 'English', 'English', '🇬🇧'),
  AppLanguage('ja', 'Japanese', '日本語', '🇯🇵'),
  AppLanguage('zh', 'Chinese', '中文', '🇨🇳'),
  AppLanguage('ko', 'Korean', '한국어', '🇰🇷'),
];

const Map<String, Map<String, String>> _strings = {
  'th': {
    'home': 'หน้าหลัก',
    'bookings': 'การจอง',
    'profile': 'โปรไฟล์',
    'hello': 'สวัสดี',
    'where_today': 'วันนี้อยากบินไปที่ไหน?',
    'special_deals': 'ดีลราคาพิเศษ',
    'popular_destinations': 'จุดหมายยอดนิยม',
    'notifications': 'การแจ้งเตือน',
    'no_notifications': 'ยังไม่มีการแจ้งเตือนใหม่',
    'one_way': 'เที่ยวเดียว',
    'round_trip': 'ไป-กลับ',
    'from': 'จาก',
    'to': 'ไป',
    'swap': 'สลับเส้นทาง',
    'cabin_class': 'ชั้นโดยสาร',
    'passengers': 'ผู้โดยสาร',
    'adult': 'ผู้ใหญ่',
    'child': 'เด็ก',
    'search_flight': 'ค้นหาเที่ยวบิน',
    'remaining': 'เหลือ',
    'seats': 'ที่นั่ง',
    'view_flights': 'ดูเที่ยวบิน',
    'no_deals': 'ยังไม่มีดีลในขณะนี้',
    'airport_transfer': 'รถบริการรับส่ง',
    'transfer_subtitle':
        'ใช้ GPS ระบุตำแหน่งรับรถ พร้อมจำนวนรถว่างแบบเรียลไทม์',
    'transfer_current_pickup': 'จุดรับปัจจุบัน',
    'transfer_available_remaining': 'รถว่างเหลือ',
    'gps_current_location': 'ตำแหน่ง GPS ปัจจุบัน',
    'gps_location_not_set': 'ยังไม่ได้ระบุตำแหน่ง',
    'gps_use_current_location': 'ใช้ตำแหน่งปัจจุบัน',
    'gps_refresh_location': 'อัปเดตตำแหน่ง GPS',
    'gps_locating': 'กำลังค้นหาตำแหน่ง...',
    'gps_accuracy': 'ความแม่นยำ',
    'gps_required': 'กรุณาระบุตำแหน่งด้วย GPS ก่อนจองรถ',
    'gps_service_disabled': 'กรุณาเปิดบริการตำแหน่ง (GPS) บนอุปกรณ์',
    'gps_permission_denied': 'ไม่ได้รับอนุญาตให้เข้าถึงตำแหน่ง',
    'gps_permission_denied_forever':
        'สิทธิ์ตำแหน่งถูกปิดถาวร กรุณาเปิดจากการตั้งค่าแอป',
    'gps_location_failed': 'ไม่สามารถระบุตำแหน่งได้ กรุณาลองอีกครั้ง',
    'gps_within_service_area': 'อยู่ในพื้นที่ให้บริการ',
    'gps_outside_service_area':
        'อยู่นอกพื้นที่ให้บริการ ต้องอยู่ห่างสนามบินไม่เกิน 20 กม.',
    'gps_distance_from_airport': 'ห่างจากสนามบิน',
    'transfer_service_radius': 'รัศมีให้บริการสูงสุด 20 กม.',
    'transfer_schedule': 'จองรถรับส่ง',
    'transfer_auto_pickup': 'ระบบกำหนดเวลารับก่อนเที่ยวบิน 3 ชั่วโมงอัตโนมัติ',
    'transfer_flight_departure': 'เวลาเที่ยวบิน',
    'transfer_pickup_time': 'เวลารับรถ',
    'transfer_locked': 'จองรถแล้ว',
    'transfer_ticket_required': 'กรุณาจองเที่ยวบินก่อนจองรถรับส่ง',
    'transfer_schedule_success': 'จองรถรับส่งแล้ว',
    'transfer_line_notification_success': 'แจ้งคนขับทาง LINE แล้ว',
    'transfer_line_notification_failed':
        'แต่ยังแจ้งคนขับทาง LINE ไม่สำเร็จ กรุณาติดต่อเจ้าหน้าที่',
    'driver': 'คนขับ',
    'cars': 'คัน',
    'economy': 'ชั้นประหยัด',
    'premium_economy': 'ชั้นประหยัดพรีเมียม',
    'business': 'ชั้นธุรกิจ',
    'first': 'ชั้นหนึ่ง',
    'my_account': 'บัญชีของฉัน',
    'preferences': 'การตั้งค่า',
    'personal_info': 'ข้อมูลส่วนตัว',
    'personal_info_sub': 'ชื่อ เบอร์โทร ที่อยู่',
    'saved_passengers': 'ผู้โดยสารที่บันทึกไว้',
    'saved_passengers_sub': 'จัดการข้อมูลผู้โดยสาร',
    'passport': 'หนังสือเดินทาง',
    'passport_sub': 'จัดการข้อมูลหนังสือเดินทาง',
    'payment_methods': 'วิธีชำระเงิน',
    'payment_methods_sub': 'บัตรและช่องทางที่บันทึกไว้',
    'dark_mode': 'โหมดมืด',
    'language': 'ภาษา',
    'choose_language': 'เลือกภาษา',
    'logout': 'ออกจากระบบ',
    'logout_confirm': 'ต้องการออกจากระบบหรือไม่?',
    'cancel': 'ยกเลิก',
    'save': 'บันทึก',
    'saved': 'บันทึกข้อมูลเรียบร้อย',
    'add': 'เพิ่ม',
    'full_name': 'ชื่อ-นามสกุล',
    'phone': 'เบอร์โทรศัพท์',
    'address': 'ที่อยู่',
    'add_passenger': 'เพิ่มผู้โดยสาร',
    'no_passengers': 'ยังไม่มีผู้โดยสารที่บันทึกไว้',
    'passport_number': 'หมายเลขหนังสือเดินทาง',
    'nationality': 'สัญชาติ',
    'my_bookings': 'การจองของฉัน',
    'flight_bookings': 'การจองเที่ยวบิน',
    'transfer_bookings': 'การจองรถรับส่ง',
    'upcoming': 'กำลังจะเดินทาง',
    'completed': 'เสร็จสิ้น',
    'cancelled': 'ยกเลิกแล้ว',
    'no_booking': 'ยังไม่มีรายการ',
    'no_booking_sub': 'การจองในสถานะนี้จะแสดงที่นี่',
    'view_ticket': 'ดูตั๋ว',
    'passenger_info': 'ข้อมูลผู้โดยสาร',
    'title': 'คำนำหน้า',
    'first_name': 'ชื่อ',
    'last_name': 'นามสกุล',
    'birth_date': 'วันเกิด',
    'passport_expiry': 'วันหมดอายุหนังสือเดินทาง',
    'required': 'กรุณากรอกข้อมูล',
    'invalid_email': 'Email ไม่ถูกต้อง',
    'select_seat': 'เลือกที่นั่ง',
    'available': 'ว่าง',
    'selected': 'ที่เลือก',
    'unavailable': 'ไม่ว่าง',
    'front': 'ด้านหน้า',
    'please_select': 'กรุณาเลือกที่นั่ง',
    'selected_seats': 'ที่นั่งที่เลือก',
    'continue': 'ดำเนินการต่อ',
    'seat_fee': 'ค่าที่นั่ง',
    'payment': 'ชำระเงิน',
    'payment_method': 'วิธีชำระเงิน',
    'scan_promptpay': 'สแกน QR PromptPay เพื่อชำระเงิน',
    'fare': 'ค่าโดยสาร',
    'airport_tax': 'ภาษีสนามบิน',
    'service_fee': 'ค่าบริการ',
    'total': 'ยอดรวม',
    'confirm_pay': 'ยืนยันและชำระเงิน',
    'mobile_bank_info': 'ระบบจำลองจะเปิดแอปธนาคารและกลับมายืนยันการชำระเงิน',
    'sort_by': 'เรียงตาม',
    'cheapest': 'ราคาถูกสุด',
    'earliest': 'ออกเร็วสุด',
    'fastest': 'บินเร็วสุด',
    'max_price': 'ราคาสูงสุด',
    'load_failed': 'โหลดเที่ยวบินไม่สำเร็จ',
    'retry': 'ลองใหม่',
    'no_flights': 'ไม่พบเที่ยวบิน',
    'no_flights_sub': 'ลองเปลี่ยนวันที่ เส้นทาง หรือช่วงราคา',
    'search_again': 'ค้นหาใหม่',
    'direct': 'บินตรง',
    'hours': 'ชม.',
    'minutes': 'นาที',
    'select': 'เลือก',
    'login_tagline': 'จองเที่ยวบินง่าย ครบทุกขั้นตอน',
    'remember_me': 'จดจำฉัน',
    'forgot_password': 'ลืมรหัสผ่าน?',
    'login': 'เข้าสู่ระบบ',
    'create_account': 'สร้างบัญชีใหม่',
    'register': 'สมัครสมาชิก',
    'register_title': 'สร้างบัญชี',
    'password_min': 'Password อย่างน้อย 6 ตัว',
    'reset_sent': 'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว',
    'download': 'ดาวน์โหลด',
    'share': 'แชร์',
    'downloaded': 'บันทึก E-Ticket แล้ว (Demo)',
    'promptpay_not_configured': 'ยังไม่ได้ตั้งค่า PROMPTPAY_ID จึงสร้าง QR รับเงินไม่ได้',
    'gateway_note': 'บัตรและ Mobile Banking ยังเป็นหน้าตัวอย่าง จนกว่าจะเชื่อมต่อ payment gateway จริง',
    'outbound_flight': 'เที่ยวบินขาไป',
    'return_flight': 'เที่ยวบินขากลับ',
    'return_date': 'วันกลับ',
    'choose_outbound': 'เลือกเที่ยวบินขาไป',
    'choose_return': 'เลือกเที่ยวบินขากลับ',
    'step_of': 'ขั้นที่ {n} จาก {total}',
    'pick_return_date': 'กรุณาเลือกวันกลับ',
    'no_return_flights': 'ไม่มีเที่ยวบินขากลับหลังเวลาที่เครื่องขาไปลงจอด',
    'search_airport': 'ค้นหาสนามบินหรือเมือง',
    'select_airport': 'เลือกสนามบิน',
    'international': 'ต่างประเทศ',
    'domestic': 'ในประเทศ',
    'seat_taken': 'ที่นั่ง {seats} ถูกจองไปแล้ว กรุณาเลือกที่นั่งใหม่',
    'booking_failed': 'จองไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    'payment_pending': 'รอยืนยันการชำระเงิน',
    'payment_pending_short': 'รอชำระ',
    'payment_pending_amount': 'ยอดชำระ {amount}',
    'payment_pending_reference': 'ใช้ Booking ID {id} เป็นหมายเหตุตอนโอน',
    'payment_pending_qr': 'QR ตั๋วจะแสดงที่นี่อัตโนมัติเมื่อยืนยันยอดเงินแล้ว',
    'ticket_qr_hint': 'QR สามารถสแกนด้วยกล้องหรือแอป QR ทั่วไปได้',
    'scan_ticket': 'สแกนตั๋ว',
    'open_scanner': 'เปิดเครื่องสแกนตั๋ว',
    'scan_e_ticket': 'สแกน E-Ticket',
    'scan_aim_hint': 'เล็งกล้องไปที่ QR บนตั๋ว NEON FLIGHT',
    'scan_checking': 'กำลังตรวจสอบกับระบบ...',
    'scan_again': 'สแกนอีกครั้ง',
    'ok': 'ตกลง',
    'ticket_invalid': 'ตั๋วไม่ถูกต้อง',
    'ticket_valid': 'ตั๋วถูกต้อง',
    'ticket_valid_body': 'ชำระเงินแล้ว และตรวจสอบกับระบบสำเร็จ',
    'ticket_not_found': 'ไม่พบตั๋วในระบบ',
    'ticket_not_found_body': 'Booking ID {id} ยังไม่ได้ยืนยันการชำระเงิน หรือไม่มีอยู่ในระบบ',
    'ticket_cancelled': 'ตั๋วถูกยกเลิก',
    'ticket_cancelled_body': 'Booking ID {id} ถูกยกเลิกแล้ว',
    'scan_offline': 'ตรวจสอบออนไลน์ไม่ได้',
    'scan_offline_body': 'Firebase ยังไม่พร้อมใช้งาน',
    'scan_failed': 'ตรวจสอบตั๋วไม่สำเร็จ',
    'route': 'เส้นทาง',
    'status': 'สถานะ',
    'qr_unreadable': 'อ่านข้อมูล QR ไม่สำเร็จ',
    'qr_bad_url': 'URL ของตั๋วไม่ถูกต้อง',
    'qr_wrong_site': 'QR นี้ไม่ใช่เว็บไซต์ตรวจตั๋ว NEON FLIGHT',
    'qr_bad_format': 'รูปแบบลิงก์ตั๋วไม่ถูกต้อง',
    'qr_not_ticket': 'QR นี้ไม่ใช่ตั๋ว NEON FLIGHT',
    'qr_incomplete': 'ข้อมูลตั๋วไม่ครบ',
    'qr_bad_token': 'รหัสตรวจสอบตั๋วไม่ถูกต้อง',
    'qr_ok': 'รูปแบบ QR ถูกต้อง',
    'share_opened': 'เปิดเมนูแชร์แล้ว (Demo)',
    'passenger': 'ผู้โดยสาร',
    'flight': 'เที่ยวบิน',
    'date': 'วันที่',
    'time': 'เวลา',
    'seat': 'ที่นั่ง',
    'class': 'ชั้นโดยสาร',
  },
  'en': {
    'home': 'Home',
    'bookings': 'Bookings',
    'profile': 'Profile',
    'hello': 'Hello',
    'where_today': 'Where would you like to fly today?',
    'special_deals': 'Special deals',
    'popular_destinations': 'Popular destinations',
    'notifications': 'Notifications',
    'no_notifications': 'No new notifications',
    'one_way': 'One way',
    'round_trip': 'Round trip',
    'from': 'From',
    'to': 'To',
    'swap': 'Swap route',
    'cabin_class': 'Cabin class',
    'passengers': 'Passengers',
    'adult': 'Adults',
    'child': 'Children',
    'search_flight': 'Search flights',
    'remaining': 'Only',
    'seats': 'seats left',
    'view_flights': 'View flights',
    'no_deals': 'No special deals available',
    'airport_transfer': 'Airport transfer',
    'transfer_subtitle':
        'Use GPS to set your pickup location with real-time availability',
    'transfer_current_pickup': 'Current pickup point',
    'transfer_available_remaining': 'Available',
    'gps_current_location': 'Current GPS location',
    'gps_location_not_set': 'Location not set',
    'gps_use_current_location': 'Use current location',
    'gps_refresh_location': 'Refresh GPS location',
    'gps_locating': 'Finding your location...',
    'gps_accuracy': 'Accuracy',
    'gps_required': 'Set your GPS location before booking a transfer',
    'gps_service_disabled': 'Turn on location services (GPS) on your device',
    'gps_permission_denied': 'Location permission was denied',
    'gps_permission_denied_forever':
        'Location permission is disabled. Enable it in app settings',
    'gps_location_failed': 'Unable to determine your location. Try again',
    'gps_within_service_area': 'Within the service area',
    'gps_outside_service_area':
        'Outside the service area. You must be within 20 km of the airport',
    'gps_distance_from_airport': 'Distance from airport',
    'transfer_service_radius': 'Maximum service radius: 20 km',
    'transfer_schedule': 'Book airport transfer',
    'transfer_auto_pickup':
        'Pickup is automatically scheduled 3 hours before departure',
    'transfer_flight_departure': 'Flight departure',
    'transfer_pickup_time': 'Pickup time',
    'transfer_locked': 'Transfer booked',
    'transfer_ticket_required': 'Book a flight before booking a transfer',
    'transfer_schedule_success': 'Airport transfer booked',
    'transfer_line_notification_success': 'Driver notified through LINE',
    'transfer_line_notification_failed':
        'Driver could not be notified through LINE. Contact support',
    'driver': 'Driver',
    'cars': 'cars',
    'economy': 'Economy Class',
    'premium_economy': 'Premium Economy',
    'business': 'Business Class',
    'first': 'First Class',
    'my_account': 'My account',
    'preferences': 'Preferences',
    'personal_info': 'Personal information',
    'personal_info_sub': 'Name, phone and address',
    'saved_passengers': 'Saved passengers',
    'saved_passengers_sub': 'Manage passenger information',
    'passport': 'Passport',
    'passport_sub': 'Manage passport information',
    'payment_methods': 'Payment methods',
    'payment_methods_sub': 'Saved cards and payment options',
    'dark_mode': 'Dark mode',
    'language': 'Language',
    'choose_language': 'Choose language',
    'logout': 'Log out',
    'logout_confirm': 'Do you want to log out?',
    'cancel': 'Cancel',
    'save': 'Save',
    'saved': 'Information saved',
    'add': 'Add',
    'full_name': 'Full name',
    'phone': 'Phone number',
    'address': 'Address',
    'add_passenger': 'Add passenger',
    'no_passengers': 'No saved passengers',
    'passport_number': 'Passport number',
    'nationality': 'Nationality',
    'my_bookings': 'My bookings',
    'flight_bookings': 'Flight bookings',
    'transfer_bookings': 'Transfer bookings',
    'upcoming': 'Upcoming',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'no_booking': 'No bookings yet',
    'no_booking_sub': 'Bookings with this status will appear here',
    'view_ticket': 'View ticket',
    'passenger_info': 'Passenger information',
    'title': 'Title',
    'first_name': 'First name',
    'last_name': 'Last name',
    'birth_date': 'Birth date',
    'passport_expiry': 'Passport expiry',
    'required': 'This field is required',
    'invalid_email': 'Invalid email',
    'select_seat': 'Select seat',
    'available': 'Available',
    'selected': 'Selected',
    'unavailable': 'Unavailable',
    'front': 'FRONT',
    'please_select': 'Please select your seat',
    'selected_seats': 'Selected seats',
    'continue': 'Continue',
    'seat_fee': 'Seat fee',
    'payment': 'Payment',
    'payment_method': 'Payment method',
    'scan_promptpay': 'Scan PromptPay QR to pay',
    'fare': 'Fare',
    'airport_tax': 'Airport tax',
    'service_fee': 'Service fee',
    'total': 'Total',
    'confirm_pay': 'Confirm and pay',
    'mobile_bank_info':
        'The demo will open a banking app and return to confirm payment',
    'sort_by': 'Sort by',
    'cheapest': 'Cheapest',
    'earliest': 'Earliest',
    'fastest': 'Fastest',
    'max_price': 'Max price',
    'load_failed': 'Could not load flights',
    'retry': 'Retry',
    'no_flights': 'No flights found',
    'no_flights_sub': 'Try another date, route, or price range',
    'search_again': 'Search again',
    'direct': 'Direct',
    'hours': 'h',
    'minutes': 'm',
    'select': 'Select',
    'login_tagline': 'Book flights easily from search to ticket',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'login': 'Log in',
    'create_account': 'Create account',
    'register': 'Register',
    'register_title': 'Create account',
    'password_min': 'Password (at least 6 characters)',
    'reset_sent': 'Password reset link sent',
    'download': 'Download',
    'share': 'Share',
    'downloaded': 'E-Ticket saved (Demo)',
    'promptpay_not_configured': 'PROMPTPAY_ID is not set, so no payment QR can be created',
    'gateway_note': 'Card and mobile banking are previews until a real payment gateway is connected',
    'outbound_flight': 'Outbound flight',
    'return_flight': 'Return flight',
    'return_date': 'Return date',
    'choose_outbound': 'Choose your outbound flight',
    'choose_return': 'Choose your return flight',
    'step_of': 'Step {n} of {total}',
    'pick_return_date': 'Please choose a return date',
    'no_return_flights': 'No return flights after your outbound flight lands',
    'search_airport': 'Search airport or city',
    'select_airport': 'Select airport',
    'international': 'International',
    'domestic': 'Domestic',
    'seat_taken': 'Seat {seats} was just taken. Please choose another seat.',
    'booking_failed': 'Booking failed. Please try again.',
    'payment_pending': 'Awaiting payment confirmation',
    'payment_pending_short': 'Payment pending',
    'payment_pending_amount': 'Amount due {amount}',
    'payment_pending_reference': 'Use booking ID {id} as the transfer reference',
    'payment_pending_qr': 'Your ticket QR appears here automatically once payment is confirmed',
    'ticket_qr_hint': 'Scan with any camera or QR app',
    'scan_ticket': 'Scan ticket',
    'open_scanner': 'Open ticket scanner',
    'scan_e_ticket': 'Scan E-Ticket',
    'scan_aim_hint': 'Point the camera at the QR on a NEON FLIGHT ticket',
    'scan_checking': 'Checking with the system...',
    'scan_again': 'Scan again',
    'ok': 'OK',
    'ticket_invalid': 'Invalid ticket',
    'ticket_valid': 'Valid ticket',
    'ticket_valid_body': 'Paid and verified with the system',
    'ticket_not_found': 'Ticket not found',
    'ticket_not_found_body': 'Booking {id} is not paid yet or does not exist',
    'ticket_cancelled': 'Ticket cancelled',
    'ticket_cancelled_body': 'Booking {id} has been cancelled',
    'scan_offline': 'Cannot verify online',
    'scan_offline_body': 'Firebase is not available',
    'scan_failed': 'Could not verify the ticket',
    'route': 'Route',
    'status': 'Status',
    'qr_unreadable': 'Could not read the QR',
    'qr_bad_url': 'Invalid ticket URL',
    'qr_wrong_site': 'This QR is not a NEON FLIGHT ticket link',
    'qr_bad_format': 'Invalid ticket link format',
    'qr_not_ticket': 'This QR is not a NEON FLIGHT ticket',
    'qr_incomplete': 'Ticket data is incomplete',
    'qr_bad_token': 'Ticket verification code is wrong',
    'qr_ok': 'QR format is valid',
    'share_opened': 'Share menu opened (Demo)',
    'passenger': 'Passenger',
    'flight': 'Flight',
    'date': 'Date',
    'time': 'Time',
    'seat': 'Seat',
    'class': 'Class',
  },
  'ja': {
    'home': 'ホーム',
    'bookings': '予約',
    'profile': 'プロフィール',
    'hello': 'こんにちは',
    'where_today': '今日はどこへ行きますか？',
    'special_deals': '特別オファー',
    'popular_destinations': '人気の目的地',
    'notifications': '通知',
    'no_notifications': '新しい通知はありません',
    'one_way': '片道',
    'round_trip': '往復',
    'from': '出発地',
    'to': '目的地',
    'swap': '入れ替え',
    'cabin_class': '座席クラス',
    'passengers': '乗客',
    'adult': '大人',
    'child': '子供',
    'search_flight': 'フライトを検索',
    'remaining': '残り',
    'seats': '席',
    'view_flights': 'フライトを見る',
    'no_deals': '現在特別オファーはありません',
    'economy': 'エコノミークラス',
    'premium_economy': 'プレミアムエコノミー',
    'business': 'ビジネスクラス',
    'first': 'ファーストクラス',
    'my_account': 'マイアカウント',
    'preferences': '設定',
    'personal_info': '個人情報',
    'personal_info_sub': '名前・電話番号・住所',
    'saved_passengers': '保存済みの乗客',
    'saved_passengers_sub': '乗客情報を管理',
    'passport': 'パスポート',
    'passport_sub': 'パスポート情報を管理',
    'payment_methods': '支払い方法',
    'payment_methods_sub': '保存済みのカードと支払い方法',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'choose_language': '言語を選択',
    'logout': 'ログアウト',
    'logout_confirm': 'ログアウトしますか？',
    'cancel': 'キャンセル',
    'save': '保存',
    'saved': '保存しました',
    'add': '追加',
    'full_name': '氏名',
    'phone': '電話番号',
    'address': '住所',
    'add_passenger': '乗客を追加',
    'no_passengers': '保存された乗客はいません',
    'passport_number': 'パスポート番号',
    'nationality': '国籍',
    'my_bookings': '予約',
    'flight_bookings': 'フライト予約',
    'transfer_bookings': '送迎予約',
    'upcoming': '今後',
    'completed': '完了',
    'cancelled': 'キャンセル済み',
    'no_booking': '予約はありません',
    'no_booking_sub': 'この状態の予約がここに表示されます',
    'view_ticket': 'チケットを見る',
    'passenger_info': '乗客情報',
    'title': '敬称',
    'first_name': '名',
    'last_name': '姓',
    'birth_date': '生年月日',
    'passport_expiry': 'パスポート有効期限',
    'required': '入力してください',
    'invalid_email': 'メールアドレスが無効です',
    'select_seat': '座席を選択',
    'available': '空席',
    'selected': '選択済み',
    'unavailable': '利用不可',
    'front': '前方',
    'please_select': '座席を選択してください',
    'selected_seats': '選択した座席',
    'continue': '続ける',
    'seat_fee': '座席料金',
    'payment': '支払い',
    'payment_method': '支払い方法',
    'scan_promptpay': 'PromptPay QRをスキャンして支払う',
    'fare': '運賃',
    'airport_tax': '空港税',
    'service_fee': 'サービス料',
    'total': '合計',
    'confirm_pay': '確認して支払う',
    'mobile_bank_info': 'デモでは銀行アプリを開き、支払い確認に戻ります',
    'sort_by': '並び替え',
    'cheapest': '最安',
    'earliest': '最早出発',
    'fastest': '最短',
    'max_price': '最高価格',
    'load_failed': 'フライトを読み込めません',
    'retry': '再試行',
    'no_flights': 'フライトが見つかりません',
    'no_flights_sub': '日付・路線・価格帯を変更してください',
    'search_again': '再検索',
    'direct': '直行便',
    'hours': '時間',
    'minutes': '分',
    'select': '選択',
    'login_tagline': '検索からチケットまで簡単に予約',
    'remember_me': 'ログイン状態を保持',
    'forgot_password': 'パスワードを忘れた場合',
    'login': 'ログイン',
    'create_account': 'アカウント作成',
    'register': '登録',
    'register_title': 'アカウント作成',
    'password_min': 'パスワード（6文字以上）',
    'reset_sent': 'リセットリンクを送信しました',
    'download': 'ダウンロード',
    'share': '共有',
    'downloaded': 'E-Ticketを保存しました（デモ）',
    'promptpay_not_configured': 'PROMPTPAY_ID が未設定のため、支払いQRを作成できません',
    'gateway_note': 'カードとモバイルバンキングは、決済ゲートウェイ接続までプレビュー表示です',
    'outbound_flight': '往路便',
    'return_flight': '復路便',
    'return_date': '復路の日付',
    'choose_outbound': '往路便を選択',
    'choose_return': '復路便を選択',
    'step_of': 'ステップ {n}/{total}',
    'pick_return_date': '復路の日付を選択してください',
    'no_return_flights': '往路便の到着後に出発する復路便がありません',
    'search_airport': '空港または都市を検索',
    'select_airport': '空港を選択',
    'international': '国際線',
    'domestic': '国内線',
    'seat_taken': '座席 {seats} は先に予約されました。別の座席を選んでください。',
    'booking_failed': '予約できませんでした。もう一度お試しください。',
    'payment_pending': 'お支払いの確認待ち',
    'payment_pending_short': '支払い待ち',
    'payment_pending_amount': 'お支払い金額 {amount}',
    'payment_pending_reference': '振込時の備考に予約番号 {id} を入力してください',
    'payment_pending_qr': '入金が確認されると、チケットのQRがここに自動で表示されます',
    'ticket_qr_hint': 'カメラや一般的なQRアプリで読み取れます',
    'scan_ticket': 'チケットをスキャン',
    'open_scanner': 'チケットスキャナーを開く',
    'scan_e_ticket': 'E-Ticketをスキャン',
    'scan_aim_hint': 'NEON FLIGHTのチケットのQRにカメラを向けてください',
    'scan_checking': 'システムで確認中...',
    'scan_again': 'もう一度スキャン',
    'ok': 'OK',
    'ticket_invalid': '無効なチケット',
    'ticket_valid': '有効なチケット',
    'ticket_valid_body': '支払い済みで、システムでの確認が完了しました',
    'ticket_not_found': 'チケットが見つかりません',
    'ticket_not_found_body': '予約 {id} は未払いか、存在しません',
    'ticket_cancelled': 'キャンセル済みのチケット',
    'ticket_cancelled_body': '予約 {id} はキャンセルされました',
    'scan_offline': 'オンラインで確認できません',
    'scan_offline_body': 'Firebaseが利用できません',
    'scan_failed': 'チケットを確認できませんでした',
    'route': '路線',
    'status': 'ステータス',
    'qr_unreadable': 'QRを読み取れませんでした',
    'qr_bad_url': 'チケットのURLが無効です',
    'qr_wrong_site': 'このQRはNEON FLIGHTのチケットではありません',
    'qr_bad_format': 'チケットリンクの形式が無効です',
    'qr_not_ticket': 'このQRはNEON FLIGHTのチケットではありません',
    'qr_incomplete': 'チケット情報が不完全です',
    'qr_bad_token': 'チケットの確認コードが正しくありません',
    'qr_ok': 'QRの形式は有効です',
    'share_opened': '共有メニューを開きました（デモ）',
    'passenger': '乗客',
    'flight': '便名',
    'date': '日付',
    'time': '時刻',
    'seat': '座席',
    'class': 'クラス',
  },
  'zh': {
    'home': '首页',
    'bookings': '预订',
    'profile': '个人资料',
    'hello': '你好',
    'where_today': '今天想飞去哪里？',
    'special_deals': '特别优惠',
    'popular_destinations': '热门目的地',
    'notifications': '通知',
    'no_notifications': '暂无新通知',
    'one_way': '单程',
    'round_trip': '往返',
    'from': '出发地',
    'to': '目的地',
    'swap': '交换路线',
    'cabin_class': '舱位',
    'passengers': '乘客',
    'adult': '成人',
    'child': '儿童',
    'search_flight': '搜索航班',
    'remaining': '剩余',
    'seats': '个座位',
    'view_flights': '查看航班',
    'no_deals': '暂无特别优惠',
    'economy': '经济舱',
    'premium_economy': '高级经济舱',
    'business': '商务舱',
    'first': '头等舱',
    'my_account': '我的账户',
    'preferences': '设置',
    'personal_info': '个人信息',
    'personal_info_sub': '姓名、电话和地址',
    'saved_passengers': '已保存乘客',
    'saved_passengers_sub': '管理乘客信息',
    'passport': '护照',
    'passport_sub': '管理护照信息',
    'payment_methods': '付款方式',
    'payment_methods_sub': '已保存的银行卡和付款方式',
    'dark_mode': '深色模式',
    'language': '语言',
    'choose_language': '选择语言',
    'logout': '退出登录',
    'logout_confirm': '确定要退出登录吗？',
    'cancel': '取消',
    'save': '保存',
    'saved': '保存成功',
    'add': '添加',
    'full_name': '姓名',
    'phone': '电话号码',
    'address': '地址',
    'add_passenger': '添加乘客',
    'no_passengers': '暂无已保存乘客',
    'passport_number': '护照号码',
    'nationality': '国籍',
    'my_bookings': '我的预订',
    'flight_bookings': '航班预订',
    'transfer_bookings': '接送预订',
    'upcoming': '即将出行',
    'completed': '已完成',
    'cancelled': '已取消',
    'no_booking': '暂无预订',
    'no_booking_sub': '此状态的预订将显示在这里',
    'view_ticket': '查看机票',
    'passenger_info': '乘客信息',
    'title': '称谓',
    'first_name': '名',
    'last_name': '姓',
    'birth_date': '出生日期',
    'passport_expiry': '护照到期日',
    'required': '请填写此项',
    'invalid_email': '邮箱格式不正确',
    'select_seat': '选择座位',
    'available': '可选',
    'selected': '已选择',
    'unavailable': '不可选',
    'front': '前方',
    'please_select': '请选择座位',
    'selected_seats': '已选座位',
    'continue': '继续',
    'seat_fee': '选座费',
    'payment': '付款',
    'payment_method': '付款方式',
    'scan_promptpay': '扫描 PromptPay 二维码付款',
    'fare': '票价',
    'airport_tax': '机场税',
    'service_fee': '服务费',
    'total': '总计',
    'confirm_pay': '确认并付款',
    'mobile_bank_info': '演示将打开银行应用并返回确认付款',
    'sort_by': '排序',
    'cheapest': '最低价',
    'earliest': '最早出发',
    'fastest': '最快',
    'max_price': '最高价格',
    'load_failed': '航班加载失败',
    'retry': '重试',
    'no_flights': '未找到航班',
    'no_flights_sub': '请尝试更改日期、航线或价格范围',
    'search_again': '重新搜索',
    'direct': '直飞',
    'hours': '小时',
    'minutes': '分钟',
    'select': '选择',
    'login_tagline': '从搜索到出票，轻松预订航班',
    'remember_me': '记住我',
    'forgot_password': '忘记密码？',
    'login': '登录',
    'create_account': '创建账户',
    'register': '注册',
    'register_title': '创建账户',
    'password_min': '密码（至少6位）',
    'reset_sent': '重置链接已发送',
    'download': '下载',
    'share': '分享',
    'downloaded': 'E-Ticket 已保存（演示）',
    'promptpay_not_configured': '未设置 PROMPTPAY_ID，无法生成收款二维码',
    'gateway_note': '在接入真实支付网关之前，银行卡和手机银行仅为预览',
    'outbound_flight': '去程航班',
    'return_flight': '返程航班',
    'return_date': '返程日期',
    'choose_outbound': '选择去程航班',
    'choose_return': '选择返程航班',
    'step_of': '第 {n} 步，共 {total} 步',
    'pick_return_date': '请选择返程日期',
    'no_return_flights': '去程航班落地后没有可选的返程航班',
    'search_airport': '搜索机场或城市',
    'select_airport': '选择机场',
    'international': '国际',
    'domestic': '国内',
    'seat_taken': '座位 {seats} 已被预订，请重新选择。',
    'booking_failed': '预订失败，请重试。',
    'payment_pending': '等待付款确认',
    'payment_pending_short': '待付款',
    'payment_pending_amount': '应付金额 {amount}',
    'payment_pending_reference': '转账时请备注预订编号 {id}',
    'payment_pending_qr': '付款确认后，机票二维码将自动显示在此处',
    'ticket_qr_hint': '可使用相机或任意二维码应用扫描',
    'scan_ticket': '扫描机票',
    'open_scanner': '打开验票扫描',
    'scan_e_ticket': '扫描电子机票',
    'scan_aim_hint': '将相机对准 NEON FLIGHT 机票上的二维码',
    'scan_checking': '正在与系统核对...',
    'scan_again': '再次扫描',
    'ok': '确定',
    'ticket_invalid': '无效机票',
    'ticket_valid': '机票有效',
    'ticket_valid_body': '已付款，系统核验通过',
    'ticket_not_found': '未找到机票',
    'ticket_not_found_body': '预订 {id} 尚未付款或不存在',
    'ticket_cancelled': '机票已取消',
    'ticket_cancelled_body': '预订 {id} 已取消',
    'scan_offline': '无法在线核验',
    'scan_offline_body': 'Firebase 不可用',
    'scan_failed': '机票核验失败',
    'route': '航线',
    'status': '状态',
    'qr_unreadable': '无法读取二维码',
    'qr_bad_url': '机票链接无效',
    'qr_wrong_site': '此二维码不是 NEON FLIGHT 机票链接',
    'qr_bad_format': '机票链接格式无效',
    'qr_not_ticket': '此二维码不是 NEON FLIGHT 机票',
    'qr_incomplete': '机票信息不完整',
    'qr_bad_token': '机票校验码错误',
    'qr_ok': '二维码格式有效',
    'share_opened': '已打开分享菜单（演示）',
    'passenger': '乘客',
    'flight': '航班',
    'date': '日期',
    'time': '时间',
    'seat': '座位',
    'class': '舱位',
  },
  'ko': {
    'home': '홈',
    'bookings': '예약',
    'profile': '프로필',
    'hello': '안녕하세요',
    'where_today': '오늘 어디로 떠나시겠어요?',
    'special_deals': '특가 상품',
    'popular_destinations': '인기 여행지',
    'notifications': '알림',
    'no_notifications': '새로운 알림이 없습니다',
    'one_way': '편도',
    'round_trip': '왕복',
    'from': '출발',
    'to': '도착',
    'swap': '경로 변경',
    'cabin_class': '좌석 등급',
    'passengers': '승객',
    'adult': '성인',
    'child': '어린이',
    'search_flight': '항공편 검색',
    'remaining': '남은 좌석',
    'seats': '석',
    'view_flights': '항공편 보기',
    'no_deals': '현재 특별 할인이 없습니다',
    'economy': '이코노미 클래스',
    'premium_economy': '프리미엄 이코노미',
    'business': '비즈니스 클래스',
    'first': '퍼스트 클래스',
    'my_account': '내 계정',
    'preferences': '설정',
    'personal_info': '개인 정보',
    'personal_info_sub': '이름, 전화번호 및 주소',
    'saved_passengers': '저장된 승객',
    'saved_passengers_sub': '승객 정보 관리',
    'passport': '여권',
    'passport_sub': '여권 정보 관리',
    'payment_methods': '결제 수단',
    'payment_methods_sub': '저장된 카드 및 결제 방법',
    'dark_mode': '다크 모드',
    'language': '언어',
    'choose_language': '언어 선택',
    'logout': '로그아웃',
    'logout_confirm': '로그아웃하시겠습니까?',
    'cancel': '취소',
    'save': '저장',
    'saved': '저장되었습니다',
    'add': '추가',
    'full_name': '이름',
    'phone': '전화번호',
    'address': '주소',
    'add_passenger': '승객 추가',
    'no_passengers': '저장된 승객이 없습니다',
    'passport_number': '여권 번호',
    'nationality': '국적',
    'my_bookings': '내 예약',
    'flight_bookings': '항공편 예약',
    'transfer_bookings': '공항 교통편 예약',
    'upcoming': '예정',
    'completed': '완료',
    'cancelled': '취소',
    'no_booking': '예약이 없습니다',
    'no_booking_sub': '이 상태의 예약이 여기에 표시됩니다',
    'view_ticket': '티켓 보기',
    'passenger_info': '승객 정보',
    'title': '호칭',
    'first_name': '이름',
    'last_name': '성',
    'birth_date': '생년월일',
    'passport_expiry': '여권 만료일',
    'required': '필수 입력 항목입니다',
    'invalid_email': '이메일 형식이 올바르지 않습니다',
    'select_seat': '좌석 선택',
    'available': '선택 가능',
    'selected': '선택됨',
    'unavailable': '사용 불가',
    'front': '앞쪽',
    'please_select': '좌석을 선택해 주세요',
    'selected_seats': '선택한 좌석',
    'continue': '계속',
    'seat_fee': '좌석 요금',
    'payment': '결제',
    'payment_method': '결제 수단',
    'scan_promptpay': 'PromptPay QR을 스캔하여 결제',
    'fare': '운임',
    'airport_tax': '공항세',
    'service_fee': '서비스 수수료',
    'total': '총액',
    'confirm_pay': '확인 및 결제',
    'mobile_bank_info': '데모에서는 은행 앱을 열고 결제 확인으로 돌아옵니다',
    'sort_by': '정렬',
    'cheapest': '최저가',
    'earliest': '가장 이른 출발',
    'fastest': '최단 시간',
    'max_price': '최고 가격',
    'load_failed': '항공편을 불러오지 못했습니다',
    'retry': '다시 시도',
    'no_flights': '항공편이 없습니다',
    'no_flights_sub': '날짜, 노선 또는 가격 범위를 변경해 보세요',
    'search_again': '다시 검색',
    'direct': '직항',
    'hours': '시간',
    'minutes': '분',
    'select': '선택',
    'login_tagline': '검색부터 티켓까지 간편하게 예약',
    'remember_me': '로그인 유지',
    'forgot_password': '비밀번호를 잊으셨나요?',
    'login': '로그인',
    'create_account': '계정 만들기',
    'register': '가입',
    'register_title': '계정 만들기',
    'password_min': '비밀번호(6자 이상)',
    'reset_sent': '재설정 링크를 보냈습니다',
    'download': '다운로드',
    'share': '공유',
    'downloaded': 'E-Ticket을 저장했습니다(데모)',
    'promptpay_not_configured': 'PROMPTPAY_ID가 설정되지 않아 결제 QR을 만들 수 없습니다',
    'gateway_note': '실제 결제 게이트웨이를 연결하기 전까지 카드와 모바일 뱅킹은 미리보기입니다',
    'outbound_flight': '가는 편',
    'return_flight': '오는 편',
    'return_date': '오는 날',
    'choose_outbound': '가는 편을 선택하세요',
    'choose_return': '오는 편을 선택하세요',
    'step_of': '{total}단계 중 {n}단계',
    'pick_return_date': '오는 날을 선택하세요',
    'no_return_flights': '가는 편 도착 이후 출발하는 오는 편이 없습니다',
    'search_airport': '공항 또는 도시 검색',
    'select_airport': '공항 선택',
    'international': '국제선',
    'domestic': '국내선',
    'seat_taken': '좌석 {seats}이(가) 이미 예약되었습니다. 다른 좌석을 선택하세요.',
    'booking_failed': '예약에 실패했습니다. 다시 시도하세요.',
    'payment_pending': '결제 확인 대기 중',
    'payment_pending_short': '결제 대기',
    'payment_pending_amount': '결제 금액 {amount}',
    'payment_pending_reference': '송금 메모에 예약 번호 {id}를 입력하세요',
    'payment_pending_qr': '결제가 확인되면 티켓 QR이 여기에 자동으로 표시됩니다',
    'ticket_qr_hint': '카메라나 일반 QR 앱으로 스캔할 수 있습니다',
    'scan_ticket': '티켓 스캔',
    'open_scanner': '티켓 스캐너 열기',
    'scan_e_ticket': 'E-Ticket 스캔',
    'scan_aim_hint': 'NEON FLIGHT 티켓의 QR에 카메라를 맞추세요',
    'scan_checking': '시스템에서 확인 중...',
    'scan_again': '다시 스캔',
    'ok': '확인',
    'ticket_invalid': '유효하지 않은 티켓',
    'ticket_valid': '유효한 티켓',
    'ticket_valid_body': '결제 완료, 시스템 확인 완료',
    'ticket_not_found': '티켓을 찾을 수 없습니다',
    'ticket_not_found_body': '예약 {id}은(는) 결제되지 않았거나 존재하지 않습니다',
    'ticket_cancelled': '취소된 티켓',
    'ticket_cancelled_body': '예약 {id}이(가) 취소되었습니다',
    'scan_offline': '온라인으로 확인할 수 없습니다',
    'scan_offline_body': 'Firebase를 사용할 수 없습니다',
    'scan_failed': '티켓을 확인하지 못했습니다',
    'route': '노선',
    'status': '상태',
    'qr_unreadable': 'QR을 읽을 수 없습니다',
    'qr_bad_url': '티켓 URL이 올바르지 않습니다',
    'qr_wrong_site': '이 QR은 NEON FLIGHT 티켓 링크가 아닙니다',
    'qr_bad_format': '티켓 링크 형식이 올바르지 않습니다',
    'qr_not_ticket': '이 QR은 NEON FLIGHT 티켓이 아닙니다',
    'qr_incomplete': '티켓 정보가 불완전합니다',
    'qr_bad_token': '티켓 확인 코드가 올바르지 않습니다',
    'qr_ok': 'QR 형식이 올바릅니다',
    'share_opened': '공유 메뉴를 열었습니다(데모)',
    'passenger': '승객',
    'flight': '항공편',
    'date': '날짜',
    'time': '시간',
    'seat': '좌석',
    'class': '클래스',
  },
};

String tr(String languageCode, String key) =>
    _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;

/// [tr] with `{name}` placeholders filled from [args].
String trArgs(String languageCode, String key, Map<String, String> args) {
  var text = tr(languageCode, key);
  args.forEach((name, value) => text = text.replaceAll('{$name}', value));
  return text;
}

String cityName(String lang, String code, {String? cityTh, String? cityEn}) {
  const map = {
    'BKK': {'ja': 'バンコク', 'zh': '曼谷', 'ko': '방콕'},
    'DMK': {'ja': 'バンコク', 'zh': '曼谷', 'ko': '방콕'},
    'CNX': {'ja': 'チェンマイ', 'zh': '清迈', 'ko': '치앙마이'},
    'HKT': {'ja': 'プーケット', 'zh': '普吉', 'ko': '푸켓'},
    'NRT': {'ja': '東京', 'zh': '东京', 'ko': '도쿄'},
    'ICN': {'ja': 'ソウル', 'zh': '首尔', 'ko': '서울'},
    'SIN': {'ja': 'シンガポール', 'zh': '新加坡', 'ko': '싱가포르'},
  };
  if (lang == 'th') return cityTh ?? code;
  if (lang == 'en') return cityEn ?? code;
  return map[code]?[lang] ?? cityEn ?? cityTh ?? code;
}
