class AppLanguage {
  const AppLanguage(this.code, this.name, this.nativeName, this.flag);
  final String code;
  final String name;
  final String nativeName;
  final String flag;
}

const supportedLanguages = <AppLanguage>[
  AppLanguage('th', 'Thai', 'ไทย', '🇹🇭'),
  AppLanguage('en', 'English', 'English', '🇬🇧'),
  AppLanguage('ja', 'Japanese', '日本語', '🇯🇵'),
  AppLanguage('zh', 'Chinese', '中文', '🇨🇳'),
  AppLanguage('ko', 'Korean', '한국어', '🇰🇷'),
];

const Map<String, Map<String, String>> _strings = {
  'th': {
    'home': 'หน้าหลัก',
    'bookings': 'การจอง',
    'profile': 'โปรไฟล์',
    'hello': 'สวัสดี',
    'where_today': 'วันนี้อยากบินไปที่ไหน?',
    'special_deals': 'ดีลราคาพิเศษ',
    'popular_destinations': 'จุดหมายยอดนิยม',
    'notifications': 'การแจ้งเตือน',
    'no_notifications': 'ยังไม่มีการแจ้งเตือนใหม่',
    'one_way': 'เที่ยวเดียว',
    'round_trip': 'ไป-กลับ',
    'from': 'จาก',
    'to': 'ไป',
    'swap': 'สลับเส้นทาง',
    'cabin_class': 'ชั้นโดยสาร',
    'passengers': 'ผู้โดยสาร',
    'adult': 'ผู้ใหญ่',
    'child': 'เด็ก',
    'search_flight': 'ค้นหาเที่ยวบิน',
    'remaining': 'เหลือ',
    'seats': 'ที่นั่ง',
    'view_flights': 'ดูเที่ยวบิน',
    'no_deals': 'ยังไม่มีดีลในขณะนี้',
    'airport_transfer': 'รถบริการรับส่ง',
    'transfer_subtitle':
        'ใช้ GPS ระบุตำแหน่งรับรถ พร้อมจำนวนรถว่างแบบเรียลไทม์',
    'transfer_current_pickup': 'จุดรับปัจจุบัน',
    'transfer_available_remaining': 'รถว่างเหลือ',
    'gps_current_location': 'ตำแหน่ง GPS ปัจจุบัน',
    'gps_location_not_set': 'ยังไม่ได้ระบุตำแหน่ง',
    'gps_use_current_location': 'ใช้ตำแหน่งปัจจุบัน',
    'gps_refresh_location': 'อัปเดตตำแหน่ง GPS',
    'gps_locating': 'กำลังค้นหาตำแหน่ง...',
    'gps_accuracy': 'ความแม่นยำ',
    'gps_required': 'กรุณาระบุตำแหน่งด้วย GPS ก่อนจองรถ',
    'gps_service_disabled': 'กรุณาเปิดบริการตำแหน่ง (GPS) บนอุปกรณ์',
    'gps_permission_denied': 'ไม่ได้รับอนุญาตให้เข้าถึงตำแหน่ง',
    'gps_permission_denied_forever':
        'สิทธิ์ตำแหน่งถูกปิดถาวร กรุณาเปิดจากการตั้งค่าแอป',
    'gps_location_failed': 'ไม่สามารถระบุตำแหน่งได้ กรุณาลองอีกครั้ง',
    'gps_within_service_area': 'อยู่ในพื้นที่ให้บริการ',
    'gps_outside_service_area':
        'อยู่นอกพื้นที่ให้บริการ ต้องอยู่ห่างสนามบินไม่เกิน 20 กม.',
    'gps_distance_from_airport': 'ห่างจากสนามบิน',
    'transfer_service_radius': 'รัศมีให้บริการสูงสุด 20 กม.',
    'transfer_schedule': 'จองรถรับส่ง',
    'transfer_auto_pickup': 'ระบบกำหนดเวลารับก่อนเที่ยวบิน 3 ชั่วโมงอัตโนมัติ',
    'transfer_flight_departure': 'เวลาเที่ยวบิน',
    'transfer_pickup_time': 'เวลารับรถ',
    'transfer_locked': 'จองรถแล้ว',
    'transfer_ticket_required': 'กรุณาจองเที่ยวบินก่อนจองรถรับส่ง',
    'transfer_schedule_success': 'จองรถรับส่งแล้ว',
    'transfer_line_notification_success': 'แจ้งคนขับทาง LINE แล้ว',
    'transfer_line_notification_failed':
        'แต่ยังแจ้งคนขับทาง LINE ไม่สำเร็จ กรุณาติดต่อเจ้าหน้าที่',
    'driver': 'คนขับ',
    'cars': 'คัน',
    'economy': 'ชั้นประหยัด',
    'premium_economy': 'ชั้นประหยัดพรีเมียม',
    'business': 'ชั้นธุรกิจ',
    'first': 'ชั้นหนึ่ง',
    'my_account': 'บัญชีของฉัน',
    'preferences': 'การตั้งค่า',
    'personal_info': 'ข้อมูลส่วนตัว',
    'personal_info_sub': 'ชื่อ เบอร์โทร ที่อยู่',
    'saved_passengers': 'ผู้โดยสารที่บันทึกไว้',
    'saved_passengers_sub': 'จัดการข้อมูลผู้โดยสาร',
    'passport': 'หนังสือเดินทาง',
    'passport_sub': 'จัดการข้อมูลหนังสือเดินทาง',
    'payment_methods': 'วิธีชำระเงิน',
    'payment_methods_sub': 'บัตรและช่องทางที่บันทึกไว้',
    'dark_mode': 'โหมดมืด',
    'language': 'ภาษา',
    'choose_language': 'เลือกภาษา',
    'logout': 'ออกจากระบบ',
    'logout_confirm': 'ต้องการออกจากระบบหรือไม่?',
    'cancel': 'ยกเลิก',
    'save': 'บันทึก',
    'saved': 'บันทึกข้อมูลเรียบร้อย',
    'add': 'เพิ่ม',
    'full_name': 'ชื่อ-นามสกุล',
    'phone': 'เบอร์โทรศัพท์',
    'address': 'ที่อยู่',
    'add_passenger': 'เพิ่มผู้โดยสาร',
    'no_passengers': 'ยังไม่มีผู้โดยสารที่บันทึกไว้',
    'passport_number': 'หมายเลขหนังสือเดินทาง',
    'nationality': 'สัญชาติ',
    'my_bookings': 'การจองของฉัน',
    'flight_bookings': 'การจองเที่ยวบิน',
    'transfer_bookings': 'การจองรถรับส่ง',
    'upcoming': 'กำลังจะเดินทาง',
    'completed': 'เสร็จสิ้น',
    'cancelled': 'ยกเลิกแล้ว',
    'no_booking': 'ยังไม่มีรายการ',
    'no_booking_sub': 'การจองในสถานะนี้จะแสดงที่นี่',
    'view_ticket': 'ดูตั๋ว',
    'passenger_info': 'ข้อมูลผู้โดยสาร',
    'title': 'คำนำหน้า',
    'first_name': 'ชื่อ',
    'last_name': 'นามสกุล',
    'birth_date': 'วันเกิด',
    'passport_expiry': 'วันหมดอายุหนังสือเดินทาง',
    'required': 'กรุณากรอกข้อมูล',
    'invalid_email': 'Email ไม่ถูกต้อง',
    'select_seat': 'เลือกที่นั่ง',
    'available': 'ว่าง',
    'selected': 'ที่เลือก',
    'unavailable': 'ไม่ว่าง',
    'front': 'ด้านหน้า',
    'please_select': 'กรุณาเลือกที่นั่ง',
    'selected_seats': 'ที่นั่งที่เลือก',
    'continue': 'ดำเนินการต่อ',
    'seat_fee': 'ค่าที่นั่ง',
    'payment': 'ชำระเงิน',
    'payment_method': 'วิธีชำระเงิน',
    'scan_promptpay': 'สแกน QR PromptPay เพื่อชำระเงิน',
    'fare': 'ค่าโดยสาร',
    'airport_tax': 'ภาษีสนามบิน',
    'service_fee': 'ค่าบริการ',
    'total': 'ยอดรวม',
    'confirm_pay': 'ยืนยันและชำระเงิน',
    'mobile_bank_info': 'ระบบจำลองจะเปิดแอปธนาคารและกลับมายืนยันการชำระเงิน',
    'sort_by': 'เรียงตาม',
    'cheapest': 'ราคาถูกสุด',
    'earliest': 'ออกเร็วสุด',
    'fastest': 'บินเร็วสุด',
    'max_price': 'ราคาสูงสุด',
    'load_failed': 'โหลดเที่ยวบินไม่สำเร็จ',
    'retry': 'ลองใหม่',
    'no_flights': 'ไม่พบเที่ยวบิน',
    'no_flights_sub': 'ลองเปลี่ยนวันที่ เส้นทาง หรือช่วงราคา',
    'search_again': 'ค้นหาใหม่',
    'direct': 'บินตรง',
    'hours': 'ชม.',
    'minutes': 'นาที',
    'select': 'เลือก',
    'login_tagline': 'จองเที่ยวบินง่าย ครบทุกขั้นตอน',
    'remember_me': 'จดจำฉัน',
    'forgot_password': 'ลืมรหัสผ่าน?',
    'login': 'เข้าสู่ระบบ',
    'create_account': 'สร้างบัญชีใหม่',
    'register': 'สมัครสมาชิก',
    'register_title': 'สร้างบัญชี',
    'password_min': 'Password อย่างน้อย 6 ตัว',
    'reset_sent': 'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว',
    'download': 'ดาวน์โหลด',
    'share': 'แชร์',
    'downloaded': 'บันทึก E-Ticket แล้ว (Demo)',
    'transfer_phase_scheduled': 'จองรถเรียบร้อย',
    'transfer_phase_driver': 'คนขับกำลังไปรับ',
    'transfer_phase_route': 'กำลังเดินทางไปสนามบิน',
    'transfer_phase_arrived': 'ถึงสนามบินแล้ว',
    'transfer_phase_cancelled': 'ยกเลิกรายการรับส่ง',
    'transfer_step_booked': 'จองแล้ว',
    'transfer_step_pickup': 'ไปรับ',
    'transfer_step_route': 'เดินทาง',
    'transfer_step_arrived': 'ถึงแล้ว',
    'auth_err_email_required': 'กรุณากรอกอีเมล',
    'auth_err_password_required': 'กรุณากรอกรหัสผ่าน',
    'auth_err_name_required': 'กรุณากรอกชื่อ',
    'auth_err_user_missing': 'ไม่พบข้อมูลผู้ใช้',
    'auth_err_password_short': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'auth_err_register_failed': 'สร้างบัญชีไม่สำเร็จ',
    'auth_err_email_invalid': 'รูปแบบอีเมลไม่ถูกต้อง',
    'auth_err_wrong_credentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
    'auth_err_email_in_use': 'อีเมลนี้ถูกใช้งานแล้ว',
    'auth_err_weak_password': 'รหัสผ่านไม่ปลอดภัยเพียงพอ',
    'auth_err_too_many': 'มีการร้องขอมากเกินไป กรุณาลองใหม่ภายหลัง',
    'auth_err_network': 'ไม่สามารถเชื่อมต่อ Firebase ได้ กรุณาตรวจสอบอินเทอร์เน็ต',
    'auth_err_not_enabled': 'ยังไม่ได้เปิด Email/Password ใน Firebase Authentication',
    'auth_err_generic': 'เกิดข้อผิดพลาดในการยืนยันตัวตน',
    'auth_err_fill_all': 'กรุณากรอกข้อมูลให้ครบ',
    'auth_err_password_mismatch': 'Password และยืนยัน Password ไม่ตรงกัน',
    'auth_err_accept_terms': 'กรุณายอมรับเงื่อนไขการใช้งานก่อนสมัครสมาชิก',
    'auth_err_login_failed': 'เข้าสู่ระบบไม่สำเร็จ',
    'auth_err_reset_failed': 'ไม่สามารถส่งลิงก์รีเซ็ตรหัสผ่านได้',
    'reset_link_sent': 'ส่งลิงก์รีเซ็ตรหัสผ่านไปที่ {email} แล้ว กรุณาตรวจสอบ Inbox หรือ Spam/Junk',
    'login_card_body': 'เข้าสู่ระบบเพื่อจองเที่ยวบิน จัดการตั๋ว และติดตามบริการรับส่ง',
    'show_password': 'แสดงรหัสผ่าน',
    'hide_password': 'ซ่อนรหัสผ่าน',
    'forgot_password_title': 'ลืมรหัสผ่าน',
    'forgot_password_body': 'กรอกอีเมลที่ใช้สมัคร Neon Flight ระบบจะส่งลิงก์สำหรับตั้งรหัสผ่านใหม่ไปยังอีเมลนั้น',
    'send_reset_link': 'ส่งลิงก์รีเซ็ต',
    'register_tagline': 'สร้างบัญชี Neon Flight เพื่อจองและจัดการทุกการเดินทางของคุณ',
    'full_name_hint': 'ชื่อและนามสกุล',
    'confirm_password': 'ยืนยัน Password',
    'accept_terms': 'ฉันยอมรับเงื่อนไขการใช้งานและนโยบายความเป็นส่วนตัว',
    'have_account': 'มีบัญชีอยู่แล้ว?',
    'use_saved_passenger': 'ใช้ข้อมูลผู้โดยสารที่บันทึกไว้',
    'choose_passenger': 'เลือกผู้โดยสาร',
    'new_passenger': 'กรอกผู้โดยสารใหม่',
    'save_passenger_next_time': 'บันทึกข้อมูลผู้โดยสารไว้ใช้ครั้งหน้า',
    'save_passenger_next_time_sub': 'ครั้งต่อไปเลือกชื่อแล้วระบบจะกรอกข้อมูลให้อัตโนมัติ',
    'welcome_to': 'ยินดีต้อนรับสู่{city}',
    'confirm_seats': 'ยืนยันที่นั่ง',
    'seat_for': 'ที่นั่ง {seat} · {name}',
    'seat_window': 'ริมหน้าต่าง',
    'seat_aisle': 'ริมทางเดิน',
    'seat_middle': 'ตรงกลาง',
    'seat_included': 'รวมในค่าโดยสาร',
    'cabin_doors_closed': 'ประตูห้องโดยสารปิดแล้ว',
    'ready_for_takeoff': 'พร้อมออกเดินทาง',
    'skip': 'ข้าม',
    'time_remaining': 'เหลือ {h} ชม. {m} นาที',
    'pay_to': 'ชำระให้ {name} · {id}',
    'save_qr': 'บันทึก QR ลงเครื่อง',
    'qr_saved': 'บันทึก QR ลงอัลบั้ม NEON FLIGHT แล้ว',
    'qr_save_denied': 'ไม่ได้รับอนุญาตให้บันทึกรูป',
    'open_bank_app': 'เปิดแอป {app}',
    'open_bank_failed': 'เปิดแอปธนาคารไม่ได้',
    'mobile_bank_steps': '1. บันทึก QR ลงเครื่อง  2. เปิดแอปธนาคาร แล้วเลือก "สแกน" › "เลือกรูป"  3. ชำระยอดตามนี้ แล้วกลับมากดยืนยันการจอง',
    'choose_bank_first': 'เลือกธนาคารที่บันทึกไว้ หรือเพิ่มในหน้าจัดการวิธีชำระเงิน',
    'per_person_incl_tax': 'ต่อท่าน รวมภาษีสนามบิน',
    'total_for_n': 'รวม {n} ท่าน {amount}',
    'estimated_fare_note': 'ราคาประเมินจากราคาตลาดจริง ภาษีสนามบินตามประกาศ ทอท.',
    'promptpay_scan_to_pay': 'สแกน QR PromptPay เพื่อชำระเงิน',
    'paid_with': 'ชำระด้วย',
    'add_payment_method': 'เพิ่มวิธีชำระเงิน',
    'payment_method_added': 'เพิ่มวิธีชำระเงินแล้ว',
    'remove_payment_method': 'ลบวิธีชำระเงินนี้?',
    'default_method': 'ค่าเริ่มต้น',
    'tap_to_make_default': 'แตะเพื่อตั้งเป็นค่าเริ่มต้น',
    'payment_privacy_note': 'แอปเก็บเฉพาะประเภทบัตร 4 หลักท้าย และวันหมดอายุ ไม่เก็บเลขบัตรเต็ม CVV รหัส OTP หรือเลขบัญชีธนาคาร',
    'promptpay_scan': 'สแกน QR เพื่อชำระเงิน',
    'promptpay_add_hint': 'จ่ายด้วยการสแกน QR จากแอปธนาคารใดก็ได้ ไม่ต้องกรอกข้อมูลเพิ่ม',
    'card_brand': 'ประเภทบัตร',
    'card_last4': 'เลขบัตร 4 หลักท้าย',
    'card_expiry': 'วันหมดอายุ',
    'invalid_last4': 'กรอกตัวเลข 4 หลัก',
    'invalid_expiry': 'รูปแบบ MM/YY',
    'card_expired': 'บัตรหมดอายุแล้ว',
    'choose_bank': 'เลือกธนาคาร',
    'set_as_default': 'ตั้งเป็นวิธีชำระเงินเริ่มต้น',
    'saved_methods': 'ที่บันทึกไว้',
    'use_new_card': 'ใช้บัตรใหม่',
    'manage_payment_methods': 'จัดการวิธีชำระเงิน',
    'notice_paid': 'ชำระเงินเรียบร้อย ตั๋วพร้อมใช้งาน',
    'notice_pending': 'รอยืนยันการชำระเงิน',
    'notice_cancelled': 'การจองถูกยกเลิก',
    'notice_soon': 'ใกล้เวลาเดินทางแล้ว',
    'notice_route_body': '{route} · {flight} · {date} {time}',
    'notice_pending_body': '{id} · ยอด {amount} · ทำรายการโอนแล้วรอแอดมินยืนยัน',
    'notifications_off_hint': 'การแจ้งเตือนปิดอยู่ในหน้าโปรไฟล์ จึงไม่แสดงจำนวนบนกระดิ่ง',
    'share_ticket': 'บันทึก / แชร์ตั๋ว',
    'share_failed': 'แชร์ตั๋วไม่สำเร็จ กรุณาลองใหม่',
    'share_ticket_text': 'E-Ticket {id}: {route} เที่ยวบิน {flight} วันที่ {date} เวลา {time}',
    'share_ticket_verify': 'ตรวจสอบตั๋ว: {url}',
    'cancel_booking': 'ยกเลิกการจอง',
    'cancel_booking_confirm': 'ยกเลิกการจอง {id}? ที่นั่งจะถูกปล่อยให้ผู้อื่นจองได้ และย้อนกลับไม่ได้',
    'cancel_trip_note': 'การจองไป-กลับจะถูกยกเลิกทั้งขาไปและขากลับ',
    'keep_booking': 'ไม่ยกเลิก',
    'booking_cancelled': 'ยกเลิกการจองแล้ว',
    'booking_cancelled_body': 'การจองนี้ถูกยกเลิกแล้ว ไม่สามารถใช้เดินทางได้',
    'cancel_failed': 'ยกเลิกไม่สำเร็จ กรุณาลองใหม่',
    'email_change_hint': 'อีเมลใช้สำหรับเข้าสู่ระบบ จึงแก้ไขจากหน้านี้ไม่ได้',
    'invalid_phone': 'เบอร์โทรศัพท์ไม่ถูกต้อง',
    'invalid_passport': 'หมายเลขหนังสือเดินทางต้องเป็นตัวอักษรหรือตัวเลข 6-9 ตัว',
    'save_failed': 'บันทึกไม่สำเร็จ กรุณาลองใหม่',
    'saved_passengers_hint': 'ผู้โดยสารจะถูกบันทึกที่นี่เมื่อคุณเลือก "บันทึกไว้ใช้ครั้งหน้า" ตอนกรอกข้อมูลการจอง',
    'delete_passenger': 'ลบผู้โดยสารที่บันทึกไว้?',
    'delete': 'ลบ',
    'choose_seat_for': 'กำลังเลือกที่นั่งให้ {name}',
    'seats_done': 'เลือกที่นั่งครบทุกคนแล้ว',
    'method_card': 'บัตร',
    'method_mobile_banking': 'โมบายแบงก์กิ้ง',
    'promptpay_not_configured': 'ร้านยังไม่ได้ตั้งเบอร์ PromptPay รับเงิน (แอดมินตั้งได้ที่หน้าแอดมิน › ตั้งค่า)',
    'gateway_note': 'บัตรและ Mobile Banking ยังเป็นหน้าตัวอย่าง จนกว่าจะเชื่อมต่อ payment gateway จริง',
    'outbound_flight': 'เที่ยวบินขาไป',
    'return_flight': 'เที่ยวบินขากลับ',
    'return_date': 'วันกลับ',
    'choose_outbound': 'เลือกเที่ยวบินขาไป',
    'choose_return': 'เลือกเที่ยวบินขากลับ',
    'step_of': 'ขั้นที่ {n} จาก {total}',
    'pick_return_date': 'กรุณาเลือกวันกลับ',
    'no_return_flights': 'ไม่มีเที่ยวบินขากลับหลังเวลาที่เครื่องขาไปลงจอด',
    'search_airport': 'ค้นหาสนามบินหรือเมือง',
    'select_airport': 'เลือกสนามบิน',
    'international': 'ต่างประเทศ',
    'domestic': 'ในประเทศ',
    'seat_taken': 'ที่นั่ง {seats} ถูกจองไปแล้ว กรุณาเลือกที่นั่งใหม่',
    'booking_failed': 'จองไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
    'payment_pending': 'รอยืนยันการชำระเงิน',
    'payment_pending_short': 'รอชำระ',
    'payment_pending_amount': 'ยอดชำระ {amount}',
    'payment_pending_reference': 'ใช้ Booking ID {id} เป็นหมายเหตุตอนโอน',
    'payment_pending_qr': 'QR ตั๋วจะแสดงที่นี่อัตโนมัติเมื่อยืนยันยอดเงินแล้ว',
    'ticket_qr_hint': 'QR สามารถสแกนด้วยกล้องหรือแอป QR ทั่วไปได้',
    'scan_ticket': 'สแกนตั๋ว',
    'open_scanner': 'เปิดเครื่องสแกนตั๋ว',
    'scan_e_ticket': 'สแกน E-Ticket',
    'scan_aim_hint': 'เล็งกล้องไปที่ QR บนตั๋ว NEON FLIGHT',
    'scan_checking': 'กำลังตรวจสอบกับระบบ...',
    'scan_again': 'สแกนอีกครั้ง',
    'ok': 'ตกลง',
    'ticket_invalid': 'ตั๋วไม่ถูกต้อง',
    'ticket_valid': 'ตั๋วถูกต้อง',
    'ticket_valid_body': 'ชำระเงินแล้ว และตรวจสอบกับระบบสำเร็จ',
    'ticket_not_found': 'ไม่พบตั๋วในระบบ',
    'ticket_not_found_body': 'Booking ID {id} ยังไม่ได้ยืนยันการชำระเงิน หรือไม่มีอยู่ในระบบ',
    'ticket_cancelled': 'ตั๋วถูกยกเลิก',
    'ticket_cancelled_body': 'Booking ID {id} ถูกยกเลิกแล้ว',
    'scan_offline': 'ตรวจสอบออนไลน์ไม่ได้',
    'scan_offline_body': 'Firebase ยังไม่พร้อมใช้งาน',
    'scan_failed': 'ตรวจสอบตั๋วไม่สำเร็จ',
    'route': 'เส้นทาง',
    'status': 'สถานะ',
    'qr_unreadable': 'อ่านข้อมูล QR ไม่สำเร็จ',
    'qr_bad_url': 'URL ของตั๋วไม่ถูกต้อง',
    'qr_wrong_site': 'QR นี้ไม่ใช่เว็บไซต์ตรวจตั๋ว NEON FLIGHT',
    'qr_bad_format': 'รูปแบบลิงก์ตั๋วไม่ถูกต้อง',
    'qr_not_ticket': 'QR นี้ไม่ใช่ตั๋ว NEON FLIGHT',
    'qr_incomplete': 'ข้อมูลตั๋วไม่ครบ',
    'qr_bad_token': 'รหัสตรวจสอบตั๋วไม่ถูกต้อง',
    'qr_ok': 'รูปแบบ QR ถูกต้อง',
    'share_opened': 'เปิดเมนูแชร์แล้ว (Demo)',
    'passenger': 'ผู้โดยสาร',
    'flight': 'เที่ยวบิน',
    'date': 'วันที่',
    'time': 'เวลา',
    'seat': 'ที่นั่ง',
    'class': 'ชั้นโดยสาร',
  },
  'en': {
    'home': 'Home',
    'bookings': 'Bookings',
    'profile': 'Profile',
    'hello': 'Hello',
    'where_today': 'Where would you like to fly today?',
    'special_deals': 'Special deals',
    'popular_destinations': 'Popular destinations',
    'notifications': 'Notifications',
    'no_notifications': 'No new notifications',
    'one_way': 'One way',
    'round_trip': 'Round trip',
    'from': 'From',
    'to': 'To',
    'swap': 'Swap route',
    'cabin_class': 'Cabin class',
    'passengers': 'Passengers',
    'adult': 'Adults',
    'child': 'Children',
    'search_flight': 'Search flights',
    'remaining': 'Only',
    'seats': 'seats left',
    'view_flights': 'View flights',
    'no_deals': 'No special deals available',
    'airport_transfer': 'Airport transfer',
    'transfer_subtitle':
        'Use GPS to set your pickup location with real-time availability',
    'transfer_current_pickup': 'Current pickup point',
    'transfer_available_remaining': 'Available',
    'gps_current_location': 'Current GPS location',
    'gps_location_not_set': 'Location not set',
    'gps_use_current_location': 'Use current location',
    'gps_refresh_location': 'Refresh GPS location',
    'gps_locating': 'Finding your location...',
    'gps_accuracy': 'Accuracy',
    'gps_required': 'Set your GPS location before booking a transfer',
    'gps_service_disabled': 'Turn on location services (GPS) on your device',
    'gps_permission_denied': 'Location permission was denied',
    'gps_permission_denied_forever':
        'Location permission is disabled. Enable it in app settings',
    'gps_location_failed': 'Unable to determine your location. Try again',
    'gps_within_service_area': 'Within the service area',
    'gps_outside_service_area':
        'Outside the service area. You must be within 20 km of the airport',
    'gps_distance_from_airport': 'Distance from airport',
    'transfer_service_radius': 'Maximum service radius: 20 km',
    'transfer_schedule': 'Book airport transfer',
    'transfer_auto_pickup':
        'Pickup is automatically scheduled 3 hours before departure',
    'transfer_flight_departure': 'Flight departure',
    'transfer_pickup_time': 'Pickup time',
    'transfer_locked': 'Transfer booked',
    'transfer_ticket_required': 'Book a flight before booking a transfer',
    'transfer_schedule_success': 'Airport transfer booked',
    'transfer_line_notification_success': 'Driver notified through LINE',
    'transfer_line_notification_failed':
        'Driver could not be notified through LINE. Contact support',
    'driver': 'Driver',
    'cars': 'cars',
    'economy': 'Economy Class',
    'premium_economy': 'Premium Economy',
    'business': 'Business Class',
    'first': 'First Class',
    'my_account': 'My account',
    'preferences': 'Preferences',
    'personal_info': 'Personal information',
    'personal_info_sub': 'Name, phone and address',
    'saved_passengers': 'Saved passengers',
    'saved_passengers_sub': 'Manage passenger information',
    'passport': 'Passport',
    'passport_sub': 'Manage passport information',
    'payment_methods': 'Payment methods',
    'payment_methods_sub': 'Saved cards and payment options',
    'dark_mode': 'Dark mode',
    'language': 'Language',
    'choose_language': 'Choose language',
    'logout': 'Log out',
    'logout_confirm': 'Do you want to log out?',
    'cancel': 'Cancel',
    'save': 'Save',
    'saved': 'Information saved',
    'add': 'Add',
    'full_name': 'Full name',
    'phone': 'Phone number',
    'address': 'Address',
    'add_passenger': 'Add passenger',
    'no_passengers': 'No saved passengers',
    'passport_number': 'Passport number',
    'nationality': 'Nationality',
    'my_bookings': 'My bookings',
    'flight_bookings': 'Flight bookings',
    'transfer_bookings': 'Transfer bookings',
    'upcoming': 'Upcoming',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'no_booking': 'No bookings yet',
    'no_booking_sub': 'Bookings with this status will appear here',
    'view_ticket': 'View ticket',
    'passenger_info': 'Passenger information',
    'title': 'Title',
    'first_name': 'First name',
    'last_name': 'Last name',
    'birth_date': 'Birth date',
    'passport_expiry': 'Passport expiry',
    'required': 'This field is required',
    'invalid_email': 'Invalid email',
    'select_seat': 'Select seat',
    'available': 'Available',
    'selected': 'Selected',
    'unavailable': 'Unavailable',
    'front': 'FRONT',
    'please_select': 'Please select your seat',
    'selected_seats': 'Selected seats',
    'continue': 'Continue',
    'seat_fee': 'Seat fee',
    'payment': 'Payment',
    'payment_method': 'Payment method',
    'scan_promptpay': 'Scan PromptPay QR to pay',
    'fare': 'Fare',
    'airport_tax': 'Airport tax',
    'service_fee': 'Service fee',
    'total': 'Total',
    'confirm_pay': 'Confirm and pay',
    'mobile_bank_info':
        'The demo will open a banking app and return to confirm payment',
    'sort_by': 'Sort by',
    'cheapest': 'Cheapest',
    'earliest': 'Earliest',
    'fastest': 'Fastest',
    'max_price': 'Max price',
    'load_failed': 'Could not load flights',
    'retry': 'Retry',
    'no_flights': 'No flights found',
    'no_flights_sub': 'Try another date, route, or price range',
    'search_again': 'Search again',
    'direct': 'Direct',
    'hours': 'h',
    'minutes': 'm',
    'select': 'Select',
    'login_tagline': 'Book flights easily from search to ticket',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'login': 'Log in',
    'create_account': 'Create account',
    'register': 'Register',
    'register_title': 'Create account',
    'password_min': 'Password (at least 6 characters)',
    'reset_sent': 'Password reset link sent',
    'download': 'Download',
    'share': 'Share',
    'downloaded': 'E-Ticket saved (Demo)',
    'transfer_phase_scheduled': 'Transfer scheduled',
    'transfer_phase_driver': 'Driver is on the way',
    'transfer_phase_route': 'On the way to the airport',
    'transfer_phase_arrived': 'Arrived at the airport',
    'transfer_phase_cancelled': 'Transfer cancelled',
    'transfer_step_booked': 'Booked',
    'transfer_step_pickup': 'Pickup',
    'transfer_step_route': 'On route',
    'transfer_step_arrived': 'Arrived',
    'auth_err_email_required': 'Please enter your email',
    'auth_err_password_required': 'Please enter your password',
    'auth_err_name_required': 'Please enter your name',
    'auth_err_user_missing': 'User not found',
    'auth_err_password_short': 'Password must be at least 6 characters',
    'auth_err_register_failed': 'Could not create the account',
    'auth_err_email_invalid': 'Invalid email address',
    'auth_err_wrong_credentials': 'Incorrect email or password',
    'auth_err_email_in_use': 'This email is already in use',
    'auth_err_weak_password': 'Password is too weak',
    'auth_err_too_many': 'Too many attempts. Please try again later',
    'auth_err_network': 'Cannot reach the server. Check your internet connection',
    'auth_err_not_enabled': 'Email/Password sign-in is not enabled in Firebase Authentication',
    'auth_err_generic': 'Authentication failed',
    'auth_err_fill_all': 'Please fill in all fields',
    'auth_err_password_mismatch': 'Passwords do not match',
    'auth_err_accept_terms': 'Please accept the terms before registering',
    'auth_err_login_failed': 'Login failed',
    'auth_err_reset_failed': 'Could not send the reset link',
    'reset_link_sent': 'Reset link sent to {email}. Check your inbox or spam folder',
    'login_card_body': 'Log in to book flights, manage tickets and track transfers',
    'show_password': 'Show password',
    'hide_password': 'Hide password',
    'forgot_password_title': 'Forgot password',
    'forgot_password_body': 'Enter the email you registered with. We will send a link to set a new password',
    'send_reset_link': 'Send reset link',
    'register_tagline': 'Create your Neon Flight account and manage every trip in one place',
    'full_name_hint': 'Full name',
    'confirm_password': 'Confirm password',
    'accept_terms': 'I agree to the Terms of Use and Privacy Policy',
    'have_account': 'Already have an account?',
    'use_saved_passenger': 'Use a saved passenger',
    'choose_passenger': 'Choose a passenger',
    'new_passenger': 'Enter a new passenger',
    'save_passenger_next_time': 'Save this passenger for next time',
    'save_passenger_next_time_sub': 'Next time, pick the name and the form fills itself',
    'welcome_to': 'Welcome to {city}',
    'confirm_seats': 'Confirm seats',
    'seat_for': 'Seat {seat} · {name}',
    'seat_window': 'Window',
    'seat_aisle': 'Aisle',
    'seat_middle': 'Middle',
    'seat_included': 'Included',
    'cabin_doors_closed': 'Cabin doors closed',
    'ready_for_takeoff': 'Ready for take-off',
    'skip': 'Skip',
    'time_remaining': '{h}h {m}m left',
    'pay_to': 'Pay to {name} · {id}',
    'save_qr': 'Save QR to photos',
    'qr_saved': 'QR saved to the NEON FLIGHT album',
    'qr_save_denied': 'Photo access was not allowed',
    'open_bank_app': 'Open {app}',
    'open_bank_failed': 'Could not open the banking app',
    'mobile_bank_steps': '1. Save the QR  2. Open your bank app, choose Scan › From photo  3. Pay this amount, then come back and confirm',
    'choose_bank_first': 'Choose a saved bank, or add one under Manage payment methods',
    'per_person_incl_tax': 'per person incl. airport tax',
    'total_for_n': '{amount} for {n} passengers',
    'estimated_fare_note': 'Fares estimated from real market prices; airport tax per AOT rates.',
    'promptpay_scan_to_pay': 'Scan the PromptPay QR to pay',
    'paid_with': 'Paid with',
    'add_payment_method': 'Add payment method',
    'payment_method_added': 'Payment method added',
    'remove_payment_method': 'Remove this payment method?',
    'default_method': 'Default',
    'tap_to_make_default': 'Tap to make default',
    'payment_privacy_note': 'Only the card brand, last 4 digits and expiry are stored. Never the full card number, CVV, OTP or bank account number.',
    'promptpay_scan': 'Pay by scanning a QR code',
    'promptpay_add_hint': 'Pay by scanning the QR with any banking app. Nothing to fill in.',
    'card_brand': 'Card type',
    'card_last4': 'Last 4 digits',
    'card_expiry': 'Expiry',
    'invalid_last4': 'Enter 4 digits',
    'invalid_expiry': 'Use MM/YY',
    'card_expired': 'Card has expired',
    'choose_bank': 'Choose a bank',
    'set_as_default': 'Use as default payment method',
    'saved_methods': 'Saved',
    'use_new_card': 'Use a new card',
    'manage_payment_methods': 'Manage payment methods',
    'notice_paid': 'Payment confirmed. Your ticket is ready',
    'notice_pending': 'Waiting for payment confirmation',
    'notice_cancelled': 'Booking cancelled',
    'notice_soon': 'Your flight is coming up',
    'notice_route_body': '{route} · {flight} · {date} {time}',
    'notice_pending_body': '{id} · {amount} · confirmed by staff after your transfer',
    'notifications_off_hint': 'Notifications are off in your profile, so the bell shows no badge',
    'share_ticket': 'Save / share ticket',
    'share_failed': 'Could not share the ticket. Please try again.',
    'share_ticket_text': 'E-Ticket {id}: {route}, flight {flight}, {date} at {time}',
    'share_ticket_verify': 'Verify: {url}',
    'cancel_booking': 'Cancel booking',
    'cancel_booking_confirm': 'Cancel booking {id}? Your seats will be released and this cannot be undone.',
    'cancel_trip_note': 'Both legs of this round trip will be cancelled.',
    'keep_booking': 'Keep booking',
    'booking_cancelled': 'Booking cancelled',
    'booking_cancelled_body': 'This booking was cancelled and cannot be used for travel.',
    'cancel_failed': 'Could not cancel. Please try again.',
    'email_change_hint': 'Email is your sign-in and cannot be changed here',
    'invalid_phone': 'Invalid phone number',
    'invalid_passport': 'Passport number must be 6-9 letters or digits',
    'save_failed': 'Could not save. Please try again.',
    'saved_passengers_hint': 'Passengers appear here when you tick "save for next time" while booking',
    'delete_passenger': 'Delete saved passenger?',
    'delete': 'Delete',
    'choose_seat_for': 'Choosing a seat for {name}',
    'seats_done': 'Seats chosen for everyone',
    'method_card': 'Card',
    'method_mobile_banking': 'Mobile banking',
    'promptpay_not_configured': 'The shop has not set its PromptPay receiving number yet (admin page › Settings)',
    'gateway_note': 'Card and mobile banking are previews until a real payment gateway is connected',
    'outbound_flight': 'Outbound flight',
    'return_flight': 'Return flight',
    'return_date': 'Return date',
    'choose_outbound': 'Choose your outbound flight',
    'choose_return': 'Choose your return flight',
    'step_of': 'Step {n} of {total}',
    'pick_return_date': 'Please choose a return date',
    'no_return_flights': 'No return flights after your outbound flight lands',
    'search_airport': 'Search airport or city',
    'select_airport': 'Select airport',
    'international': 'International',
    'domestic': 'Domestic',
    'seat_taken': 'Seat {seats} was just taken. Please choose another seat.',
    'booking_failed': 'Booking failed. Please try again.',
    'payment_pending': 'Awaiting payment confirmation',
    'payment_pending_short': 'Payment pending',
    'payment_pending_amount': 'Amount due {amount}',
    'payment_pending_reference': 'Use booking ID {id} as the transfer reference',
    'payment_pending_qr': 'Your ticket QR appears here automatically once payment is confirmed',
    'ticket_qr_hint': 'Scan with any camera or QR app',
    'scan_ticket': 'Scan ticket',
    'open_scanner': 'Open ticket scanner',
    'scan_e_ticket': 'Scan E-Ticket',
    'scan_aim_hint': 'Point the camera at the QR on a NEON FLIGHT ticket',
    'scan_checking': 'Checking with the system...',
    'scan_again': 'Scan again',
    'ok': 'OK',
    'ticket_invalid': 'Invalid ticket',
    'ticket_valid': 'Valid ticket',
    'ticket_valid_body': 'Paid and verified with the system',
    'ticket_not_found': 'Ticket not found',
    'ticket_not_found_body': 'Booking {id} is not paid yet or does not exist',
    'ticket_cancelled': 'Ticket cancelled',
    'ticket_cancelled_body': 'Booking {id} has been cancelled',
    'scan_offline': 'Cannot verify online',
    'scan_offline_body': 'Firebase is not available',
    'scan_failed': 'Could not verify the ticket',
    'route': 'Route',
    'status': 'Status',
    'qr_unreadable': 'Could not read the QR',
    'qr_bad_url': 'Invalid ticket URL',
    'qr_wrong_site': 'This QR is not a NEON FLIGHT ticket link',
    'qr_bad_format': 'Invalid ticket link format',
    'qr_not_ticket': 'This QR is not a NEON FLIGHT ticket',
    'qr_incomplete': 'Ticket data is incomplete',
    'qr_bad_token': 'Ticket verification code is wrong',
    'qr_ok': 'QR format is valid',
    'share_opened': 'Share menu opened (Demo)',
    'passenger': 'Passenger',
    'flight': 'Flight',
    'date': 'Date',
    'time': 'Time',
    'seat': 'Seat',
    'class': 'Class',
  },
  'ja': {
    'home': 'ホーム',
    'bookings': '予約',
    'profile': 'プロフィール',
    'hello': 'こんにちは',
    'where_today': '今日はどこへ行きますか？',
    'special_deals': '特別オファー',
    'popular_destinations': '人気の目的地',
    'notifications': '通知',
    'no_notifications': '新しい通知はありません',
    'one_way': '片道',
    'round_trip': '往復',
    'from': '出発地',
    'to': '目的地',
    'swap': '入れ替え',
    'cabin_class': '座席クラス',
    'passengers': '乗客',
    'adult': '大人',
    'child': '子供',
    'search_flight': 'フライトを検索',
    'remaining': '残り',
    'seats': '席',
    'view_flights': 'フライトを見る',
    'no_deals': '現在特別オファーはありません',
    'economy': 'エコノミークラス',
    'premium_economy': 'プレミアムエコノミー',
    'business': 'ビジネスクラス',
    'first': 'ファーストクラス',
    'my_account': 'マイアカウント',
    'preferences': '設定',
    'personal_info': '個人情報',
    'personal_info_sub': '名前・電話番号・住所',
    'saved_passengers': '保存済みの乗客',
    'saved_passengers_sub': '乗客情報を管理',
    'passport': 'パスポート',
    'passport_sub': 'パスポート情報を管理',
    'payment_methods': '支払い方法',
    'payment_methods_sub': '保存済みのカードと支払い方法',
    'dark_mode': 'ダークモード',
    'language': '言語',
    'choose_language': '言語を選択',
    'logout': 'ログアウト',
    'logout_confirm': 'ログアウトしますか？',
    'cancel': 'キャンセル',
    'save': '保存',
    'saved': '保存しました',
    'add': '追加',
    'full_name': '氏名',
    'phone': '電話番号',
    'address': '住所',
    'add_passenger': '乗客を追加',
    'no_passengers': '保存された乗客はいません',
    'passport_number': 'パスポート番号',
    'nationality': '国籍',
    'my_bookings': '予約',
    'flight_bookings': 'フライト予約',
    'transfer_bookings': '送迎予約',
    'upcoming': '今後',
    'completed': '完了',
    'cancelled': 'キャンセル済み',
    'no_booking': '予約はありません',
    'no_booking_sub': 'この状態の予約がここに表示されます',
    'view_ticket': 'チケットを見る',
    'passenger_info': '乗客情報',
    'title': '敬称',
    'first_name': '名',
    'last_name': '姓',
    'birth_date': '生年月日',
    'passport_expiry': 'パスポート有効期限',
    'required': '入力してください',
    'invalid_email': 'メールアドレスが無効です',
    'select_seat': '座席を選択',
    'available': '空席',
    'selected': '選択済み',
    'unavailable': '利用不可',
    'front': '前方',
    'please_select': '座席を選択してください',
    'selected_seats': '選択した座席',
    'continue': '続ける',
    'seat_fee': '座席料金',
    'payment': '支払い',
    'payment_method': '支払い方法',
    'scan_promptpay': 'PromptPay QRをスキャンして支払う',
    'fare': '運賃',
    'airport_tax': '空港税',
    'service_fee': 'サービス料',
    'total': '合計',
    'confirm_pay': '確認して支払う',
    'mobile_bank_info': 'デモでは銀行アプリを開き、支払い確認に戻ります',
    'sort_by': '並び替え',
    'cheapest': '最安',
    'earliest': '最早出発',
    'fastest': '最短',
    'max_price': '最高価格',
    'load_failed': 'フライトを読み込めません',
    'retry': '再試行',
    'no_flights': 'フライトが見つかりません',
    'no_flights_sub': '日付・路線・価格帯を変更してください',
    'search_again': '再検索',
    'direct': '直行便',
    'hours': '時間',
    'minutes': '分',
    'select': '選択',
    'login_tagline': '検索からチケットまで簡単に予約',
    'remember_me': 'ログイン状態を保持',
    'forgot_password': 'パスワードを忘れた場合',
    'login': 'ログイン',
    'create_account': 'アカウント作成',
    'register': '登録',
    'register_title': 'アカウント作成',
    'password_min': 'パスワード（6文字以上）',
    'reset_sent': 'リセットリンクを送信しました',
    'download': 'ダウンロード',
    'share': '共有',
    'downloaded': 'E-Ticketを保存しました（デモ）',
    'transfer_phase_scheduled': '送迎を手配しました',
    'transfer_phase_driver': 'ドライバーがお迎えに向かっています',
    'transfer_phase_route': '空港へ移動中',
    'transfer_phase_arrived': '空港に到着しました',
    'transfer_phase_cancelled': '送迎はキャンセルされました',
    'transfer_step_booked': '予約済み',
    'transfer_step_pickup': 'お迎え',
    'transfer_step_route': '移動中',
    'transfer_step_arrived': '到着',
    'auth_err_email_required': 'メールアドレスを入力してください',
    'auth_err_password_required': 'パスワードを入力してください',
    'auth_err_name_required': '名前を入力してください',
    'auth_err_user_missing': 'ユーザーが見つかりません',
    'auth_err_password_short': 'パスワードは6文字以上にしてください',
    'auth_err_register_failed': 'アカウントを作成できませんでした',
    'auth_err_email_invalid': 'メールアドレスの形式が正しくありません',
    'auth_err_wrong_credentials': 'メールアドレスまたはパスワードが正しくありません',
    'auth_err_email_in_use': 'このメールアドレスは既に使用されています',
    'auth_err_weak_password': 'パスワードが弱すぎます',
    'auth_err_too_many': '試行回数が多すぎます。しばらくしてから再試行してください',
    'auth_err_network': 'サーバーに接続できません。インターネット接続を確認してください',
    'auth_err_not_enabled': 'Firebase Authentication でメール/パスワードが有効になっていません',
    'auth_err_generic': '認証に失敗しました',
    'auth_err_fill_all': 'すべての項目を入力してください',
    'auth_err_password_mismatch': 'パスワードが一致しません',
    'auth_err_accept_terms': '登録前に利用規約に同意してください',
    'auth_err_login_failed': 'ログインできませんでした',
    'auth_err_reset_failed': 'リセットリンクを送信できませんでした',
    'reset_link_sent': '{email} にリセットリンクを送信しました。受信トレイまたは迷惑メールを確認してください',
    'login_card_body': 'ログインして航空券の予約、チケット管理、送迎の確認ができます',
    'show_password': 'パスワードを表示',
    'hide_password': 'パスワードを隠す',
    'forgot_password_title': 'パスワードを忘れた場合',
    'forgot_password_body': '登録したメールアドレスを入力すると、新しいパスワードを設定するリンクを送信します',
    'send_reset_link': 'リセットリンクを送信',
    'register_tagline': 'Neon Flight アカウントを作成して、すべての旅をまとめて管理',
    'full_name_hint': '氏名',
    'confirm_password': 'パスワード（確認）',
    'accept_terms': '利用規約とプライバシーポリシーに同意します',
    'have_account': 'アカウントをお持ちですか？',
    'use_saved_passenger': '保存済みの搭乗者を使う',
    'choose_passenger': '搭乗者を選択',
    'new_passenger': '新しい搭乗者を入力',
    'save_passenger_next_time': 'この搭乗者を次回のために保存',
    'save_passenger_next_time_sub': '次回は名前を選ぶだけで自動入力されます',
    'welcome_to': '{city}へようこそ',
    'confirm_seats': '座席を確定',
    'seat_for': '座席 {seat} · {name}',
    'seat_window': '窓側',
    'seat_aisle': '通路側',
    'seat_middle': '中央',
    'seat_included': '運賃に含む',
    'cabin_doors_closed': '客室ドアが閉まりました',
    'ready_for_takeoff': 'まもなく離陸します',
    'skip': 'スキップ',
    'time_remaining': '残り {h}時間{m}分',
    'pay_to': '支払先 {name} · {id}',
    'save_qr': 'QRを写真に保存',
    'qr_saved': 'QRをNEON FLIGHTアルバムに保存しました',
    'qr_save_denied': '写真へのアクセスが許可されませんでした',
    'open_bank_app': '{app}を開く',
    'open_bank_failed': '銀行アプリを開けませんでした',
    'mobile_bank_steps': '1. QRを保存  2. 銀行アプリで「スキャン」›「写真から」  3. この金額を支払い、戻って予約を確定',
    'choose_bank_first': '保存済みの銀行を選ぶか、支払い方法の管理で追加してください',
    'per_person_incl_tax': '1名あたり・空港税込み',
    'total_for_n': '{n}名で {amount}',
    'estimated_fare_note': '運賃は実勢価格に基づく目安です。空港税はAOTの規定どおりです。',
    'promptpay_scan_to_pay': 'PromptPayのQRを読み取って支払う',
    'paid_with': '支払い方法',
    'add_payment_method': '支払い方法を追加',
    'payment_method_added': '支払い方法を追加しました',
    'remove_payment_method': 'この支払い方法を削除しますか？',
    'default_method': 'デフォルト',
    'tap_to_make_default': 'タップしてデフォルトに設定',
    'payment_privacy_note': 'カードのブランド、下4桁、有効期限のみ保存します。カード番号全体、CVV、OTP、口座番号は保存しません。',
    'promptpay_scan': 'QRコードで支払い',
    'promptpay_add_hint': 'どの銀行アプリでもQRを読み取って支払えます。入力は不要です。',
    'card_brand': 'カードの種類',
    'card_last4': 'カード番号の下4桁',
    'card_expiry': '有効期限',
    'invalid_last4': '4桁の数字を入力',
    'invalid_expiry': 'MM/YY 形式',
    'card_expired': '有効期限切れです',
    'choose_bank': '銀行を選択',
    'set_as_default': 'デフォルトの支払い方法にする',
    'saved_methods': '保存済み',
    'use_new_card': '新しいカードを使う',
    'manage_payment_methods': '支払い方法を管理',
    'notice_paid': 'お支払いを確認しました。チケットをご利用いただけます',
    'notice_pending': 'お支払いの確認待ち',
    'notice_cancelled': '予約がキャンセルされました',
    'notice_soon': 'まもなくご出発です',
    'notice_route_body': '{route} · {flight} · {date} {time}',
    'notice_pending_body': '{id} · {amount} · 振込後にスタッフが確認します',
    'notifications_off_hint': 'プロフィールで通知がオフのため、ベルに件数は表示されません',
    'share_ticket': 'チケットを保存・共有',
    'share_failed': 'チケットを共有できませんでした。もう一度お試しください。',
    'share_ticket_text': 'E-Ticket {id}：{route}　{flight}便　{date} {time}',
    'share_ticket_verify': '確認: {url}',
    'cancel_booking': '予約をキャンセル',
    'cancel_booking_confirm': '予約 {id} をキャンセルしますか？座席は解放され、元に戻せません。',
    'cancel_trip_note': '往復の往路・復路の両方がキャンセルされます。',
    'keep_booking': 'キャンセルしない',
    'booking_cancelled': '予約をキャンセルしました',
    'booking_cancelled_body': 'この予約はキャンセル済みのため、搭乗には使えません。',
    'cancel_failed': 'キャンセルできませんでした。もう一度お試しください。',
    'email_change_hint': 'メールはログインに使うため、ここでは変更できません',
    'invalid_phone': '電話番号が正しくありません',
    'invalid_passport': '旅券番号は英数字6〜9文字です',
    'save_failed': '保存できませんでした。もう一度お試しください。',
    'saved_passengers_hint': '予約時に「次回のために保存」を選ぶと、ここに表示されます',
    'delete_passenger': '保存した搭乗者を削除しますか？',
    'delete': '削除',
    'choose_seat_for': '{name} さんの座席を選択中',
    'seats_done': '全員の座席を選択しました',
    'method_card': 'カード',
    'method_mobile_banking': 'モバイルバンキング',
    'promptpay_not_configured': 'お店のPromptPay受取番号が未設定です（管理画面 › 設定）',
    'gateway_note': 'カードとモバイルバンキングは、決済ゲートウェイ接続までプレビュー表示です',
    'outbound_flight': '往路便',
    'return_flight': '復路便',
    'return_date': '復路の日付',
    'choose_outbound': '往路便を選択',
    'choose_return': '復路便を選択',
    'step_of': 'ステップ {n}/{total}',
    'pick_return_date': '復路の日付を選択してください',
    'no_return_flights': '往路便の到着後に出発する復路便がありません',
    'search_airport': '空港または都市を検索',
    'select_airport': '空港を選択',
    'international': '国際線',
    'domestic': '国内線',
    'seat_taken': '座席 {seats} は先に予約されました。別の座席を選んでください。',
    'booking_failed': '予約できませんでした。もう一度お試しください。',
    'payment_pending': 'お支払いの確認待ち',
    'payment_pending_short': '支払い待ち',
    'payment_pending_amount': 'お支払い金額 {amount}',
    'payment_pending_reference': '振込時の備考に予約番号 {id} を入力してください',
    'payment_pending_qr': '入金が確認されると、チケットのQRがここに自動で表示されます',
    'ticket_qr_hint': 'カメラや一般的なQRアプリで読み取れます',
    'scan_ticket': 'チケットをスキャン',
    'open_scanner': 'チケットスキャナーを開く',
    'scan_e_ticket': 'E-Ticketをスキャン',
    'scan_aim_hint': 'NEON FLIGHTのチケットのQRにカメラを向けてください',
    'scan_checking': 'システムで確認中...',
    'scan_again': 'もう一度スキャン',
    'ok': 'OK',
    'ticket_invalid': '無効なチケット',
    'ticket_valid': '有効なチケット',
    'ticket_valid_body': '支払い済みで、システムでの確認が完了しました',
    'ticket_not_found': 'チケットが見つかりません',
    'ticket_not_found_body': '予約 {id} は未払いか、存在しません',
    'ticket_cancelled': 'キャンセル済みのチケット',
    'ticket_cancelled_body': '予約 {id} はキャンセルされました',
    'scan_offline': 'オンラインで確認できません',
    'scan_offline_body': 'Firebaseが利用できません',
    'scan_failed': 'チケットを確認できませんでした',
    'route': '路線',
    'status': 'ステータス',
    'qr_unreadable': 'QRを読み取れませんでした',
    'qr_bad_url': 'チケットのURLが無効です',
    'qr_wrong_site': 'このQRはNEON FLIGHTのチケットではありません',
    'qr_bad_format': 'チケットリンクの形式が無効です',
    'qr_not_ticket': 'このQRはNEON FLIGHTのチケットではありません',
    'qr_incomplete': 'チケット情報が不完全です',
    'qr_bad_token': 'チケットの確認コードが正しくありません',
    'qr_ok': 'QRの形式は有効です',
    'share_opened': '共有メニューを開きました（デモ）',
    'passenger': '乗客',
    'flight': '便名',
    'date': '日付',
    'time': '時刻',
    'seat': '座席',
    'class': 'クラス',
  },
  'zh': {
    'home': '首页',
    'bookings': '预订',
    'profile': '个人资料',
    'hello': '你好',
    'where_today': '今天想飞去哪里？',
    'special_deals': '特别优惠',
    'popular_destinations': '热门目的地',
    'notifications': '通知',
    'no_notifications': '暂无新通知',
    'one_way': '单程',
    'round_trip': '往返',
    'from': '出发地',
    'to': '目的地',
    'swap': '交换路线',
    'cabin_class': '舱位',
    'passengers': '乘客',
    'adult': '成人',
    'child': '儿童',
    'search_flight': '搜索航班',
    'remaining': '剩余',
    'seats': '个座位',
    'view_flights': '查看航班',
    'no_deals': '暂无特别优惠',
    'economy': '经济舱',
    'premium_economy': '高级经济舱',
    'business': '商务舱',
    'first': '头等舱',
    'my_account': '我的账户',
    'preferences': '设置',
    'personal_info': '个人信息',
    'personal_info_sub': '姓名、电话和地址',
    'saved_passengers': '已保存乘客',
    'saved_passengers_sub': '管理乘客信息',
    'passport': '护照',
    'passport_sub': '管理护照信息',
    'payment_methods': '付款方式',
    'payment_methods_sub': '已保存的银行卡和付款方式',
    'dark_mode': '深色模式',
    'language': '语言',
    'choose_language': '选择语言',
    'logout': '退出登录',
    'logout_confirm': '确定要退出登录吗？',
    'cancel': '取消',
    'save': '保存',
    'saved': '保存成功',
    'add': '添加',
    'full_name': '姓名',
    'phone': '电话号码',
    'address': '地址',
    'add_passenger': '添加乘客',
    'no_passengers': '暂无已保存乘客',
    'passport_number': '护照号码',
    'nationality': '国籍',
    'my_bookings': '我的预订',
    'flight_bookings': '航班预订',
    'transfer_bookings': '接送预订',
    'upcoming': '即将出行',
    'completed': '已完成',
    'cancelled': '已取消',
    'no_booking': '暂无预订',
    'no_booking_sub': '此状态的预订将显示在这里',
    'view_ticket': '查看机票',
    'passenger_info': '乘客信息',
    'title': '称谓',
    'first_name': '名',
    'last_name': '姓',
    'birth_date': '出生日期',
    'passport_expiry': '护照到期日',
    'required': '请填写此项',
    'invalid_email': '邮箱格式不正确',
    'select_seat': '选择座位',
    'available': '可选',
    'selected': '已选择',
    'unavailable': '不可选',
    'front': '前方',
    'please_select': '请选择座位',
    'selected_seats': '已选座位',
    'continue': '继续',
    'seat_fee': '选座费',
    'payment': '付款',
    'payment_method': '付款方式',
    'scan_promptpay': '扫描 PromptPay 二维码付款',
    'fare': '票价',
    'airport_tax': '机场税',
    'service_fee': '服务费',
    'total': '总计',
    'confirm_pay': '确认并付款',
    'mobile_bank_info': '演示将打开银行应用并返回确认付款',
    'sort_by': '排序',
    'cheapest': '最低价',
    'earliest': '最早出发',
    'fastest': '最快',
    'max_price': '最高价格',
    'load_failed': '航班加载失败',
    'retry': '重试',
    'no_flights': '未找到航班',
    'no_flights_sub': '请尝试更改日期、航线或价格范围',
    'search_again': '重新搜索',
    'direct': '直飞',
    'hours': '小时',
    'minutes': '分钟',
    'select': '选择',
    'login_tagline': '从搜索到出票，轻松预订航班',
    'remember_me': '记住我',
    'forgot_password': '忘记密码？',
    'login': '登录',
    'create_account': '创建账户',
    'register': '注册',
    'register_title': '创建账户',
    'password_min': '密码（至少6位）',
    'reset_sent': '重置链接已发送',
    'download': '下载',
    'share': '分享',
    'downloaded': 'E-Ticket 已保存（演示）',
    'transfer_phase_scheduled': '接送已预订',
    'transfer_phase_driver': '司机正在前往接您',
    'transfer_phase_route': '正在前往机场',
    'transfer_phase_arrived': '已到达机场',
    'transfer_phase_cancelled': '接送已取消',
    'transfer_step_booked': '已预订',
    'transfer_step_pickup': '接载',
    'transfer_step_route': '途中',
    'transfer_step_arrived': '已到达',
    'auth_err_email_required': '请输入电子邮件',
    'auth_err_password_required': '请输入密码',
    'auth_err_name_required': '请输入姓名',
    'auth_err_user_missing': '未找到用户',
    'auth_err_password_short': '密码至少需要 6 个字符',
    'auth_err_register_failed': '无法创建账户',
    'auth_err_email_invalid': '电子邮件格式不正确',
    'auth_err_wrong_credentials': '电子邮件或密码不正确',
    'auth_err_email_in_use': '该电子邮件已被使用',
    'auth_err_weak_password': '密码强度不足',
    'auth_err_too_many': '尝试次数过多，请稍后再试',
    'auth_err_network': '无法连接服务器，请检查网络',
    'auth_err_not_enabled': 'Firebase Authentication 未启用电子邮件/密码登录',
    'auth_err_generic': '身份验证失败',
    'auth_err_fill_all': '请填写所有字段',
    'auth_err_password_mismatch': '两次输入的密码不一致',
    'auth_err_accept_terms': '注册前请先同意条款',
    'auth_err_login_failed': '登录失败',
    'auth_err_reset_failed': '无法发送重置链接',
    'reset_link_sent': '已将重置链接发送至 {email}，请检查收件箱或垃圾邮件',
    'login_card_body': '登录以预订航班、管理机票并跟踪接送服务',
    'show_password': '显示密码',
    'hide_password': '隐藏密码',
    'forgot_password_title': '忘记密码',
    'forgot_password_body': '输入注册时使用的电子邮件，我们将发送设置新密码的链接',
    'send_reset_link': '发送重置链接',
    'register_tagline': '创建 Neon Flight 账户，集中管理每一次旅行',
    'full_name_hint': '姓名',
    'confirm_password': '确认密码',
    'accept_terms': '我同意使用条款和隐私政策',
    'have_account': '已有账户？',
    'use_saved_passenger': '使用已保存的乘客',
    'choose_passenger': '选择乘客',
    'new_passenger': '填写新乘客',
    'save_passenger_next_time': '保存此乘客以便下次使用',
    'save_passenger_next_time_sub': '下次选择姓名即可自动填写',
    'welcome_to': '欢迎来到{city}',
    'confirm_seats': '确认座位',
    'seat_for': '座位 {seat} · {name}',
    'seat_window': '靠窗',
    'seat_aisle': '靠过道',
    'seat_middle': '中间',
    'seat_included': '已含在票价中',
    'cabin_doors_closed': '舱门已关闭',
    'ready_for_takeoff': '准备起飞',
    'skip': '跳过',
    'time_remaining': '剩余 {h} 小时 {m} 分',
    'pay_to': '收款方 {name} · {id}',
    'save_qr': '保存二维码到相册',
    'qr_saved': '二维码已保存到 NEON FLIGHT 相册',
    'qr_save_denied': '未获得相册权限',
    'open_bank_app': '打开 {app}',
    'open_bank_failed': '无法打开银行应用',
    'mobile_bank_steps': '1. 保存二维码  2. 打开银行应用，选择“扫码”›“从相册”  3. 支付该金额后返回确认预订',
    'choose_bank_first': '请选择已保存的银行，或在“管理付款方式”中添加',
    'per_person_incl_tax': '每人，含机场税',
    'total_for_n': '{n} 位乘客共 {amount}',
    'estimated_fare_note': '票价依据真实市场价格估算，机场税按 AOT 标准收取。',
    'promptpay_scan_to_pay': '扫描 PromptPay 二维码付款',
    'paid_with': '付款方式',
    'add_payment_method': '添加付款方式',
    'payment_method_added': '已添加付款方式',
    'remove_payment_method': '删除此付款方式？',
    'default_method': '默认',
    'tap_to_make_default': '点按设为默认',
    'payment_privacy_note': '仅保存卡组织、后四位和有效期，不保存完整卡号、CVV、OTP 或银行账号。',
    'promptpay_scan': '扫描二维码付款',
    'promptpay_add_hint': '使用任意银行应用扫描二维码付款，无需填写信息。',
    'card_brand': '卡组织',
    'card_last4': '卡号后四位',
    'card_expiry': '有效期',
    'invalid_last4': '请输入 4 位数字',
    'invalid_expiry': '格式为 MM/YY',
    'card_expired': '卡已过期',
    'choose_bank': '选择银行',
    'set_as_default': '设为默认付款方式',
    'saved_methods': '已保存',
    'use_new_card': '使用新卡',
    'manage_payment_methods': '管理付款方式',
    'notice_paid': '付款已确认，机票可以使用了',
    'notice_pending': '等待付款确认',
    'notice_cancelled': '预订已取消',
    'notice_soon': '航班即将出发',
    'notice_route_body': '{route} · {flight} · {date} {time}',
    'notice_pending_body': '{id} · {amount} · 转账后由工作人员确认',
    'notifications_off_hint': '个人资料中已关闭通知，铃铛不显示数量',
    'share_ticket': '保存 / 分享机票',
    'share_failed': '分享机票失败，请重试。',
    'share_ticket_text': '电子机票 {id}：{route}，航班 {flight}，{date} {time}',
    'share_ticket_verify': '验证: {url}',
    'cancel_booking': '取消预订',
    'cancel_booking_confirm': '取消预订 {id}？座位将被释放，且无法撤销。',
    'cancel_trip_note': '往返行程的去程和返程都将被取消。',
    'keep_booking': '保留预订',
    'booking_cancelled': '预订已取消',
    'booking_cancelled_body': '此预订已取消，不能用于出行。',
    'cancel_failed': '取消失败，请重试。',
    'email_change_hint': '邮箱用于登录，无法在此修改',
    'invalid_phone': '电话号码无效',
    'invalid_passport': '护照号码须为 6-9 位字母或数字',
    'save_failed': '保存失败，请重试。',
    'saved_passengers_hint': '预订时勾选“保存以便下次使用”的乘客会显示在这里',
    'delete_passenger': '删除已保存的乘客？',
    'delete': '删除',
    'choose_seat_for': '正在为 {name} 选座',
    'seats_done': '已为所有人选好座位',
    'method_card': '银行卡',
    'method_mobile_banking': '手机银行',
    'promptpay_not_configured': '商家尚未设置 PromptPay 收款号码（管理页 › 设置）',
    'gateway_note': '在接入真实支付网关之前，银行卡和手机银行仅为预览',
    'outbound_flight': '去程航班',
    'return_flight': '返程航班',
    'return_date': '返程日期',
    'choose_outbound': '选择去程航班',
    'choose_return': '选择返程航班',
    'step_of': '第 {n} 步，共 {total} 步',
    'pick_return_date': '请选择返程日期',
    'no_return_flights': '去程航班落地后没有可选的返程航班',
    'search_airport': '搜索机场或城市',
    'select_airport': '选择机场',
    'international': '国际',
    'domestic': '国内',
    'seat_taken': '座位 {seats} 已被预订，请重新选择。',
    'booking_failed': '预订失败，请重试。',
    'payment_pending': '等待付款确认',
    'payment_pending_short': '待付款',
    'payment_pending_amount': '应付金额 {amount}',
    'payment_pending_reference': '转账时请备注预订编号 {id}',
    'payment_pending_qr': '付款确认后，机票二维码将自动显示在此处',
    'ticket_qr_hint': '可使用相机或任意二维码应用扫描',
    'scan_ticket': '扫描机票',
    'open_scanner': '打开验票扫描',
    'scan_e_ticket': '扫描电子机票',
    'scan_aim_hint': '将相机对准 NEON FLIGHT 机票上的二维码',
    'scan_checking': '正在与系统核对...',
    'scan_again': '再次扫描',
    'ok': '确定',
    'ticket_invalid': '无效机票',
    'ticket_valid': '机票有效',
    'ticket_valid_body': '已付款，系统核验通过',
    'ticket_not_found': '未找到机票',
    'ticket_not_found_body': '预订 {id} 尚未付款或不存在',
    'ticket_cancelled': '机票已取消',
    'ticket_cancelled_body': '预订 {id} 已取消',
    'scan_offline': '无法在线核验',
    'scan_offline_body': 'Firebase 不可用',
    'scan_failed': '机票核验失败',
    'route': '航线',
    'status': '状态',
    'qr_unreadable': '无法读取二维码',
    'qr_bad_url': '机票链接无效',
    'qr_wrong_site': '此二维码不是 NEON FLIGHT 机票链接',
    'qr_bad_format': '机票链接格式无效',
    'qr_not_ticket': '此二维码不是 NEON FLIGHT 机票',
    'qr_incomplete': '机票信息不完整',
    'qr_bad_token': '机票校验码错误',
    'qr_ok': '二维码格式有效',
    'share_opened': '已打开分享菜单（演示）',
    'passenger': '乘客',
    'flight': '航班',
    'date': '日期',
    'time': '时间',
    'seat': '座位',
    'class': '舱位',
  },
  'ko': {
    'home': '홈',
    'bookings': '예약',
    'profile': '프로필',
    'hello': '안녕하세요',
    'where_today': '오늘 어디로 떠나시겠어요?',
    'special_deals': '특가 상품',
    'popular_destinations': '인기 여행지',
    'notifications': '알림',
    'no_notifications': '새로운 알림이 없습니다',
    'one_way': '편도',
    'round_trip': '왕복',
    'from': '출발',
    'to': '도착',
    'swap': '경로 변경',
    'cabin_class': '좌석 등급',
    'passengers': '승객',
    'adult': '성인',
    'child': '어린이',
    'search_flight': '항공편 검색',
    'remaining': '남은 좌석',
    'seats': '석',
    'view_flights': '항공편 보기',
    'no_deals': '현재 특별 할인이 없습니다',
    'economy': '이코노미 클래스',
    'premium_economy': '프리미엄 이코노미',
    'business': '비즈니스 클래스',
    'first': '퍼스트 클래스',
    'my_account': '내 계정',
    'preferences': '설정',
    'personal_info': '개인 정보',
    'personal_info_sub': '이름, 전화번호 및 주소',
    'saved_passengers': '저장된 승객',
    'saved_passengers_sub': '승객 정보 관리',
    'passport': '여권',
    'passport_sub': '여권 정보 관리',
    'payment_methods': '결제 수단',
    'payment_methods_sub': '저장된 카드 및 결제 방법',
    'dark_mode': '다크 모드',
    'language': '언어',
    'choose_language': '언어 선택',
    'logout': '로그아웃',
    'logout_confirm': '로그아웃하시겠습니까?',
    'cancel': '취소',
    'save': '저장',
    'saved': '저장되었습니다',
    'add': '추가',
    'full_name': '이름',
    'phone': '전화번호',
    'address': '주소',
    'add_passenger': '승객 추가',
    'no_passengers': '저장된 승객이 없습니다',
    'passport_number': '여권 번호',
    'nationality': '국적',
    'my_bookings': '내 예약',
    'flight_bookings': '항공편 예약',
    'transfer_bookings': '공항 교통편 예약',
    'upcoming': '예정',
    'completed': '완료',
    'cancelled': '취소',
    'no_booking': '예약이 없습니다',
    'no_booking_sub': '이 상태의 예약이 여기에 표시됩니다',
    'view_ticket': '티켓 보기',
    'passenger_info': '승객 정보',
    'title': '호칭',
    'first_name': '이름',
    'last_name': '성',
    'birth_date': '생년월일',
    'passport_expiry': '여권 만료일',
    'required': '필수 입력 항목입니다',
    'invalid_email': '이메일 형식이 올바르지 않습니다',
    'select_seat': '좌석 선택',
    'available': '선택 가능',
    'selected': '선택됨',
    'unavailable': '사용 불가',
    'front': '앞쪽',
    'please_select': '좌석을 선택해 주세요',
    'selected_seats': '선택한 좌석',
    'continue': '계속',
    'seat_fee': '좌석 요금',
    'payment': '결제',
    'payment_method': '결제 수단',
    'scan_promptpay': 'PromptPay QR을 스캔하여 결제',
    'fare': '운임',
    'airport_tax': '공항세',
    'service_fee': '서비스 수수료',
    'total': '총액',
    'confirm_pay': '확인 및 결제',
    'mobile_bank_info': '데모에서는 은행 앱을 열고 결제 확인으로 돌아옵니다',
    'sort_by': '정렬',
    'cheapest': '최저가',
    'earliest': '가장 이른 출발',
    'fastest': '최단 시간',
    'max_price': '최고 가격',
    'load_failed': '항공편을 불러오지 못했습니다',
    'retry': '다시 시도',
    'no_flights': '항공편이 없습니다',
    'no_flights_sub': '날짜, 노선 또는 가격 범위를 변경해 보세요',
    'search_again': '다시 검색',
    'direct': '직항',
    'hours': '시간',
    'minutes': '분',
    'select': '선택',
    'login_tagline': '검색부터 티켓까지 간편하게 예약',
    'remember_me': '로그인 유지',
    'forgot_password': '비밀번호를 잊으셨나요?',
    'login': '로그인',
    'create_account': '계정 만들기',
    'register': '가입',
    'register_title': '계정 만들기',
    'password_min': '비밀번호(6자 이상)',
    'reset_sent': '재설정 링크를 보냈습니다',
    'download': '다운로드',
    'share': '공유',
    'downloaded': 'E-Ticket을 저장했습니다(데모)',
    'transfer_phase_scheduled': '픽업 예약 완료',
    'transfer_phase_driver': '기사가 픽업하러 가는 중',
    'transfer_phase_route': '공항으로 이동 중',
    'transfer_phase_arrived': '공항 도착',
    'transfer_phase_cancelled': '픽업 취소됨',
    'transfer_step_booked': '예약됨',
    'transfer_step_pickup': '픽업',
    'transfer_step_route': '이동 중',
    'transfer_step_arrived': '도착',
    'auth_err_email_required': '이메일을 입력하세요',
    'auth_err_password_required': '비밀번호를 입력하세요',
    'auth_err_name_required': '이름을 입력하세요',
    'auth_err_user_missing': '사용자를 찾을 수 없습니다',
    'auth_err_password_short': '비밀번호는 6자 이상이어야 합니다',
    'auth_err_register_failed': '계정을 만들 수 없습니다',
    'auth_err_email_invalid': '이메일 형식이 올바르지 않습니다',
    'auth_err_wrong_credentials': '이메일 또는 비밀번호가 올바르지 않습니다',
    'auth_err_email_in_use': '이미 사용 중인 이메일입니다',
    'auth_err_weak_password': '비밀번호가 너무 약합니다',
    'auth_err_too_many': '시도 횟수가 너무 많습니다. 나중에 다시 시도하세요',
    'auth_err_network': '서버에 연결할 수 없습니다. 인터넷 연결을 확인하세요',
    'auth_err_not_enabled': 'Firebase Authentication에서 이메일/비밀번호가 활성화되지 않았습니다',
    'auth_err_generic': '인증에 실패했습니다',
    'auth_err_fill_all': '모든 항목을 입력하세요',
    'auth_err_password_mismatch': '비밀번호가 일치하지 않습니다',
    'auth_err_accept_terms': '가입하기 전에 약관에 동의하세요',
    'auth_err_login_failed': '로그인에 실패했습니다',
    'auth_err_reset_failed': '재설정 링크를 보낼 수 없습니다',
    'reset_link_sent': '{email}(으)로 재설정 링크를 보냈습니다. 받은편지함 또는 스팸함을 확인하세요',
    'login_card_body': '로그인하여 항공편 예약, 티켓 관리, 픽업 서비스를 확인하세요',
    'show_password': '비밀번호 표시',
    'hide_password': '비밀번호 숨기기',
    'forgot_password_title': '비밀번호 찾기',
    'forgot_password_body': '가입한 이메일을 입력하면 새 비밀번호 설정 링크를 보내드립니다',
    'send_reset_link': '재설정 링크 보내기',
    'register_tagline': 'Neon Flight 계정을 만들고 모든 여행을 한곳에서 관리하세요',
    'full_name_hint': '이름',
    'confirm_password': '비밀번호 확인',
    'accept_terms': '이용약관 및 개인정보 처리방침에 동의합니다',
    'have_account': '이미 계정이 있으신가요?',
    'use_saved_passenger': '저장된 승객 사용',
    'choose_passenger': '승객 선택',
    'new_passenger': '새 승객 입력',
    'save_passenger_next_time': '다음을 위해 이 승객 저장',
    'save_passenger_next_time_sub': '다음에는 이름만 선택하면 자동으로 입력됩니다',
    'welcome_to': '{city}에 오신 것을 환영합니다',
    'confirm_seats': '좌석 확정',
    'seat_for': '좌석 {seat} · {name}',
    'seat_window': '창가',
    'seat_aisle': '통로',
    'seat_middle': '가운데',
    'seat_included': '요금 포함',
    'cabin_doors_closed': '객실 문이 닫혔습니다',
    'ready_for_takeoff': '이륙 준비 완료',
    'skip': '건너뛰기',
    'time_remaining': '{h}시간 {m}분 남음',
    'pay_to': '받는 곳 {name} · {id}',
    'save_qr': 'QR을 사진에 저장',
    'qr_saved': 'QR을 NEON FLIGHT 앨범에 저장했습니다',
    'qr_save_denied': '사진 접근이 허용되지 않았습니다',
    'open_bank_app': '{app} 열기',
    'open_bank_failed': '은행 앱을 열 수 없습니다',
    'mobile_bank_steps': '1. QR 저장  2. 은행 앱에서 스캔 › 사진에서 선택  3. 금액 결제 후 돌아와 예약 확정',
    'choose_bank_first': '저장된 은행을 선택하거나 결제 수단 관리에서 추가하세요',
    'per_person_incl_tax': '1인당 · 공항세 포함',
    'total_for_n': '{n}명 합계 {amount}',
    'estimated_fare_note': '요금은 실제 시장 가격 기반 추정치이며, 공항세는 AOT 기준입니다.',
    'promptpay_scan_to_pay': 'PromptPay QR을 스캔해 결제',
    'paid_with': '결제 수단',
    'add_payment_method': '결제 수단 추가',
    'payment_method_added': '결제 수단을 추가했습니다',
    'remove_payment_method': '이 결제 수단을 삭제할까요?',
    'default_method': '기본',
    'tap_to_make_default': '탭하여 기본으로 설정',
    'payment_privacy_note': '카드 브랜드, 끝 4자리, 유효기간만 저장하며 전체 카드 번호, CVV, OTP, 계좌 번호는 저장하지 않습니다.',
    'promptpay_scan': 'QR 코드로 결제',
    'promptpay_add_hint': '어떤 은행 앱으로도 QR을 스캔해 결제할 수 있습니다. 입력할 내용은 없습니다.',
    'card_brand': '카드 종류',
    'card_last4': '카드 번호 끝 4자리',
    'card_expiry': '유효기간',
    'invalid_last4': '숫자 4자리를 입력하세요',
    'invalid_expiry': 'MM/YY 형식',
    'card_expired': '만료된 카드입니다',
    'choose_bank': '은행 선택',
    'set_as_default': '기본 결제 수단으로 사용',
    'saved_methods': '저장됨',
    'use_new_card': '새 카드 사용',
    'manage_payment_methods': '결제 수단 관리',
    'notice_paid': '결제가 확인되었습니다. 티켓을 사용할 수 있습니다',
    'notice_pending': '결제 확인 대기 중',
    'notice_cancelled': '예약이 취소되었습니다',
    'notice_soon': '곧 출발합니다',
    'notice_route_body': '{route} · {flight} · {date} {time}',
    'notice_pending_body': '{id} · {amount} · 송금 후 직원이 확인합니다',
    'notifications_off_hint': '프로필에서 알림이 꺼져 있어 종에 숫자가 표시되지 않습니다',
    'share_ticket': '티켓 저장 / 공유',
    'share_failed': '티켓을 공유하지 못했습니다. 다시 시도하세요.',
    'share_ticket_text': 'E-Ticket {id}: {route}, {flight}편, {date} {time}',
    'share_ticket_verify': '확인: {url}',
    'cancel_booking': '예약 취소',
    'cancel_booking_confirm': '예약 {id}을(를) 취소할까요? 좌석이 해제되며 되돌릴 수 없습니다.',
    'cancel_trip_note': '왕복 예약의 가는 편과 오는 편이 모두 취소됩니다.',
    'keep_booking': '유지하기',
    'booking_cancelled': '예약이 취소되었습니다',
    'booking_cancelled_body': '이 예약은 취소되어 탑승에 사용할 수 없습니다.',
    'cancel_failed': '취소하지 못했습니다. 다시 시도하세요.',
    'email_change_hint': '이메일은 로그인에 사용되어 여기서 변경할 수 없습니다',
    'invalid_phone': '전화번호가 올바르지 않습니다',
    'invalid_passport': '여권 번호는 영문/숫자 6~9자여야 합니다',
    'save_failed': '저장하지 못했습니다. 다시 시도하세요.',
    'saved_passengers_hint': '예약 시 "다음을 위해 저장"을 선택한 승객이 여기에 표시됩니다',
    'delete_passenger': '저장된 승객을 삭제할까요?',
    'delete': '삭제',
    'choose_seat_for': '{name}님의 좌석을 선택 중',
    'seats_done': '모든 승객의 좌석을 선택했습니다',
    'method_card': '카드',
    'method_mobile_banking': '모바일 뱅킹',
    'promptpay_not_configured': '판매자의 PromptPay 수취 번호가 아직 설정되지 않았습니다(관리자 페이지 › 설정)',
    'gateway_note': '실제 결제 게이트웨이를 연결하기 전까지 카드와 모바일 뱅킹은 미리보기입니다',
    'outbound_flight': '가는 편',
    'return_flight': '오는 편',
    'return_date': '오는 날',
    'choose_outbound': '가는 편을 선택하세요',
    'choose_return': '오는 편을 선택하세요',
    'step_of': '{total}단계 중 {n}단계',
    'pick_return_date': '오는 날을 선택하세요',
    'no_return_flights': '가는 편 도착 이후 출발하는 오는 편이 없습니다',
    'search_airport': '공항 또는 도시 검색',
    'select_airport': '공항 선택',
    'international': '국제선',
    'domestic': '국내선',
    'seat_taken': '좌석 {seats}이(가) 이미 예약되었습니다. 다른 좌석을 선택하세요.',
    'booking_failed': '예약에 실패했습니다. 다시 시도하세요.',
    'payment_pending': '결제 확인 대기 중',
    'payment_pending_short': '결제 대기',
    'payment_pending_amount': '결제 금액 {amount}',
    'payment_pending_reference': '송금 메모에 예약 번호 {id}를 입력하세요',
    'payment_pending_qr': '결제가 확인되면 티켓 QR이 여기에 자동으로 표시됩니다',
    'ticket_qr_hint': '카메라나 일반 QR 앱으로 스캔할 수 있습니다',
    'scan_ticket': '티켓 스캔',
    'open_scanner': '티켓 스캐너 열기',
    'scan_e_ticket': 'E-Ticket 스캔',
    'scan_aim_hint': 'NEON FLIGHT 티켓의 QR에 카메라를 맞추세요',
    'scan_checking': '시스템에서 확인 중...',
    'scan_again': '다시 스캔',
    'ok': '확인',
    'ticket_invalid': '유효하지 않은 티켓',
    'ticket_valid': '유효한 티켓',
    'ticket_valid_body': '결제 완료, 시스템 확인 완료',
    'ticket_not_found': '티켓을 찾을 수 없습니다',
    'ticket_not_found_body': '예약 {id}은(는) 결제되지 않았거나 존재하지 않습니다',
    'ticket_cancelled': '취소된 티켓',
    'ticket_cancelled_body': '예약 {id}이(가) 취소되었습니다',
    'scan_offline': '온라인으로 확인할 수 없습니다',
    'scan_offline_body': 'Firebase를 사용할 수 없습니다',
    'scan_failed': '티켓을 확인하지 못했습니다',
    'route': '노선',
    'status': '상태',
    'qr_unreadable': 'QR을 읽을 수 없습니다',
    'qr_bad_url': '티켓 URL이 올바르지 않습니다',
    'qr_wrong_site': '이 QR은 NEON FLIGHT 티켓 링크가 아닙니다',
    'qr_bad_format': '티켓 링크 형식이 올바르지 않습니다',
    'qr_not_ticket': '이 QR은 NEON FLIGHT 티켓이 아닙니다',
    'qr_incomplete': '티켓 정보가 불완전합니다',
    'qr_bad_token': '티켓 확인 코드가 올바르지 않습니다',
    'qr_ok': 'QR 형식이 올바릅니다',
    'share_opened': '공유 메뉴를 열었습니다(데모)',
    'passenger': '승객',
    'flight': '항공편',
    'date': '날짜',
    'time': '시간',
    'seat': '좌석',
    'class': '클래스',
  },
};

String tr(String languageCode, String key) =>
    _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;

/// [tr] with `{name}` placeholders filled from [args].
String trArgs(String languageCode, String key, Map<String, String> args) {
  var text = tr(languageCode, key);
  args.forEach((name, value) => text = text.replaceAll('{$name}', value));
  return text;
}

String cityName(String lang, String code, {String? cityTh, String? cityEn}) {
  const map = {
    'BKK': {'ja': 'バンコク', 'zh': '曼谷', 'ko': '방콕'},
    'DMK': {'ja': 'バンコク', 'zh': '曼谷', 'ko': '방콕'},
    'CNX': {'ja': 'チェンマイ', 'zh': '清迈', 'ko': '치앙마이'},
    'HKT': {'ja': 'プーケット', 'zh': '普吉', 'ko': '푸켓'},
    'NRT': {'ja': '東京', 'zh': '东京', 'ko': '도쿄'},
    'ICN': {'ja': 'ソウル', 'zh': '首尔', 'ko': '서울'},
    'SIN': {'ja': 'シンガポール', 'zh': '新加坡', 'ko': '싱가포르'},
  };
  if (lang == 'th') return cityTh ?? code;
  if (lang == 'en') return cityEn ?? code;
  return map[code]?[lang] ?? cityEn ?? cityTh ?? code;
}
